### ISSUE TITLE
Step table handling error 

### ISSUE THREAD

**Issue by Srinivasaraor** [trivago/cucable-plugin#100]
**Describe the bug**
Throwing error when the step table value is not defined in the example table column.
Same issue is observed with Scenario and ScenarioOutline.
Below scenario outline is working fine with cucumber.

**To Reproduce**
1.    Scenario Outline: Check for specialties for an Expert Witness
    Given a new request is created for the "test" user and "profilesuite" user
    And the "Accept" header is set to "application/atom+xml"
    And the path parameter "entityId" is "<witness_id>"
    When the "GET" request is called for "PROFILE"
    Then the response code is "200"
    And the response body contains following text:
      | <profile:specialties>  |
      | </profile:specialties> |

    Examples:
      | witness_id|
      | 268290 |
      | 439377 |
      | 277529 |
2. Run Cucable
3. INFO] - generated   2 scenarios from src\test\resources\features\analytics\Context-Retrieve-Profile.feature.
[INFO] - generated   2 scenarios from src\test\resources\features\analytics\Context-Search-Retrieve.feature.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.170 s
[INFO] Finished at: 2019-03-07T14:11:39-05:00
[INFO] Final Memory: 28M/427M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.trivago.rta:cucable-plugin:1.4.0:parallel (generate-test-resources) on project infra-shared-services-tests: Execution generate-test-resources of goal com.trivago.rta:cucable-plugin:1.4.0:parallel failed: In scenario outline placeholder "<profile:specialties>" is not listed in the "Examples" table. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

Process finished with exit code 1

**Expected behavior**
step table should be handled properly , 
**Attachments**
If applicable, add an attachment to help explain your problem.

**Additional context**
Please let me know if you need further details on this issue.

**Comment by laxersaz** [comment]
Hello @Srinivasaraor ,
yes you are correct - this is indeed a bug which should be fairly easy to fix. I will tackle this one and release it soon.

**Comment by Srinivasaraor** [comment]
Thanks for your quick response

**Comment by laxersaz** [comment]
Available in 1.5.0
