### ISSUE TITLE
would it possible to pass tagging logic in include and exclude ScenarioTags

### ISSUE THREAD

**Issue by Srinivasaraor** [trivago/cucable-plugin#102]
**Is your feature request related to a problem? Please describe.**
i am looking to pass below tagging logic to pick certain test tagged with dvt, is it possible via cucable plugin
 '(@archive or @reg-gb or @manual or @ignore or @partial or @bcd or @stf) and (@dvt)'

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by laxersaz** [comment]
As you can only set a global `and` or `or` connection for included tags, this is not possible with Cucable alone at the moment. However, you could use the `includeScenarioTags` property of Cucable with your `@DVT` tag - this would generate all features that include this tag. Then, in your runner file, you could filter out all features that don't contain `@archive`, `@reg-gb`, `@Manual`, `@ignore`, `@partial`, `@bcd` or `@stf`.
That means that in your case, more features then you actually need might be created but you would not run all of them.

**Comment by Srinivasaraor** [comment]
How about having only "<scenarioTags></scenarioTags> instead of <includeScenarioTags> and <excludeScenarioTags> by allowing AND,OR, NOT logic to it , this implementation will allow us to write more complex tagging logic to generate desired feature files . Please let me know your thoughts.
Thank you 
Srinivas

**Comment by laxersaz** [comment]
Personally I think this would be nice to support the Cucumber 4 way of specifying tag logic, e.g. `(@smoke or @ui) and (not @slow)` (taken from https://docs.cucumber.io/cucumber/api/#tags). The downside is that the implementation is not that trivial.
