### ISSUE TITLE
Not able to run when Step Definition in a .jar file

### ISSUE THREAD

**Issue by jaydeepqa** [trivago/cucable-plugin#105]
I am having my Step Definitions code/file in a .jar file which I imported in project build path in Eclipse, but my feature file and Test Runner file is not in .jar.
Now when I am trying to run my tests getting error "You can implement missing steps with the snippets below:" actually TestRunner file's glue is not able to find Step Definitions in a .jar file.
Do I need to mention something explicitly in TestRunner glue to make it identify Step Definition in .jar?

**Comment by laxersaz** [comment]
This question is unrelated to Cucable. Cucable just splits features into smaller parallelizable parts based on a template file. So it runs __before__ the tests are executed.

**Comment by jaydeepqa** [comment]
Got it, still from your personal experience can you give some info about
how we can achieve this.

**Comment by laxersaz** [comment]
Sorry, @jaydeepqa , but this is not a general Cucumber support forum. As this is a side project, I unfortunately don't have the resources to answer questions outside of this project.
