### ISSUE TITLE
Missing scenario with cucumber tag expression

### ISSUE THREAD

**Issue by boris779** [trivago/cucable-plugin#107]
Since I upgraded to cucable 1.5, one scenario is not recognized

I run exactly the same testset with Version 1.3 and 1.5 to compare

`

10:36:01 [INFO]  Cucable Maven Plugin, version 1.3.0
10:36:01 [INFO] -------------------------------------
10:36:01 [INFO] - sourceRunnerTemplateFile  : 
src/test/resources/parallel/cucable.template/CucableJavaTemplate.java
10:36:01 [INFO] - generatedRunnerDirectory  : /home/jenkins/workspace/ure.....
10:36:01 [INFO] - sourceFeatures            : src/test/resources/features
10:36:01 [INFO] - excludeScenarioTags       : @ignore, @mobileOnly
10:36:01 [INFO] - parallelizationMode       : SCENARIOS
10:36:01 [INFO] - generatedFeatureDirectory : /home/jenkins/workspace/ure_...
10:36:01 [INFO] - numberOfTestRuns          : 1
10:36:01 [INFO] -------------------------------------
10:36:01 [INFO] -   1  scenario from src/test/resources/features/Mieterstammdaten.feature.
10:36:01 [INFO] -   1  scenario from src/test/resources/features/Hofinformationen.feature.
10:36:01 [INFO] -   3 scenarios from src/test/resources/features/Registration.feature.
10:36:01 [INFO] -   0 scenarios from src/test/resources/features/Mobile.feature.
10:36:01 [INFO] -   1  scenario from src/test/resources/features/Mietzinskonto.feature.
10:36:01 [INFO] -   2 scenarios from src/test/resources/features/Cookies.feature.
10:36:01 [INFO] -   2 scenarios from src/test/resources/features/Navigation.feature.
10:36:01 [INFO] -   4 scenarios from src/test/resources/features/Feedback.feature.
10:36:01 [INFO] -   2 scenarios from src/test/resources/features/StatischeSeiten.feature.
10:36:01 [INFO] -------------------------------------
10:36:01 [INFO] Cucable created 16 separate feature files and 16 runners.`

`

Cucable Maven Plugin, version 1.5.0
11:06:16 [INFO] -------------------------------------

11:06:16 [INFO] - sourceFeatures               :
11:06:16 [INFO]   - src/test/resources/features
11:06:16 [INFO] - sourceRunnerTemplateFile     : src/test/resources/parallel/cucable.template/CucableJavaTemplate.java
11:06:16 [INFO] -------------------------------------
11:06:16 [INFO] - generatedRunnerDirectory     : /home/jenkins/workspace/ure_KUN.....
11:06:16 [INFO] - generatedFeatureDirectory    : /home/jenkins/workspace/ure_KUN-....
11:06:16 [INFO] -------------------------------------
11:06:16 [INFO] - includeScenarioTags          : not @mobileOnly and not @ignore
11:06:16 [INFO] - parallelizationMode          : scenarios
11:06:16 [INFO] - numberOfTestRuns             : 1
11:06:16 [INFO] -------------------------------------
11:06:16 [INFO] - generated   2 scenarios from src/test/resources/features/Navigation.feature.
11:06:16 [INFO] - generated   4 scenarios from src/test/resources/features/Feedback.feature.
11:06:16 [INFO] - generated   0 scenarios from src/test/resources/features/Mobile.feature.
11:06:16 [INFO] - generated   1  scenario from src/test/resources/features/Mieterstammdaten.feature.
11:06:16 [INFO] - generated   2 scenarios from src/test/resources/features/StatischeSeiten.feature.
11:06:16 [INFO] - generated   2 scenarios from src/test/resources/features/Cookies.feature.
11:06:16 [INFO] - generated   2 scenarios from src/test/resources/features/Registration.feature.
11:06:16 [INFO] - generated   1  scenario from src/test/resources/features/Mietzinskonto.feature.
11:06:16 [INFO] - generated   1  scenario from src/test/resources/features/Hofinformationen.feature.
11:06:16 [INFO] -------------------------------------
11:06:16 [INFO] Cucable created 15 separate feature files and 15 runners.`

The Registration.feature looks like this, the RG-05 scenario is missing! I also tried to move it around in the file, no idea why this scenario gets ignored.

`
\# language: de
\# encoding: utf-8
Funktionalität: [RG [Registration]

\#header für die Startseite notwendig!
  @smoke @mobile
  Szenario: [RG-01 [Registration] Schönwetter
    Angenommen die Registrierungsseite ist geladen
    Und ein Benutzer mit gültigen Werten registriert wird
    Dann sollte die Alles fertig Seite angezeigt werden
    Und es sollte nach 5 Sekunden die Startseite des Kundenportals angezeigt werden

  @smoke
  Szenario: [RG-02 [Registration] Versucht mit ungültigen Werten
    Wenn die Registrierungsseite geladen ist
    Und alle Felder mit ungültigen Werten ausgefüllt werden
    Dann bleibe ich auf der Registrierungsseite

\#Szenario: [RG-03 [Registration] Versuch mit bereits registrierter Servicecard Nummer
 \# gelöscht wegen geänderter Fachlichkeit

  \#Szenario: [RG-04 [Registration] Validierung Servicekarten und Kundennummer Happytest
  \#duplicate to RG-01 after changing behaviour

  Szenario: [RG-05 [Registration] Neg. Validierung Servicekarten und Kundennummer Errortest
    Wenn die Registrierungsseite geladen ist
    Und ein neuer Benutzer mit "1234567890" und "as12" registriert wird
    Dann sollte eine Fehlermeldung "Die eingegebene Nummer und der Sicherheits-Code passen nicht zusammen oder stimmen nicht." angezeigt werden
`

**Comment by laxersaz** [comment]
Thanks for reporting, I will investigate this. If you give your RG-05 scenario any tag (e.g. @dummy), is in included?

**Comment by laxersaz** [comment]
I found the bug and fixed it for release 1.5.1 - it should be available on Maven central soon. Please try it @boris779 and let me know if this fixes it.

**Comment by boris779** [comment]
Sorry for delay. 
it works now :-)
Thx for the fast fix.
