### ISSUE TITLE
Runner file generated with the feature/scenario Name

### ISSUE THREAD

**Issue by ajmera25** [trivago/cucable-plugin#108]
Currently I can see when I generate runner on the basis of scenario then it is generated something like "MyFeature_scenario001_run001_IT". What I want is that runner name should include the scenario name.
So it can be like example "ScenarioName",FeatureName_ScenarioName or any custom as per user.

It Just a thought. Reason why i said so because with runner file name I should be able to know this is for which feature/scenario file. This will help me when I run through jenkins/TestNG Selective Run.

Thanks

**Comment by laxersaz** [comment]
Hello @ajmera25 
can you elaborate a little more why this would help you when you run through Jenkins? Because Cucable is designed to select and filter while generating test resources so that you don't have to filter again when you run those generated resources.

**Comment by laxersaz** [comment]
Closed because of no further activity.
