### ISSUE TITLE
Initializing classes inside the runner

### ISSUE THREAD

**Issue by VinnieM** [trivago/cucable-plugin#110]
This might be a very trivial question. As per my design I am loading all my required classes (initializing Selenium/Appium library, Test data and other stuff) in the Runner class. How do I initialize all the required stuff in the CucableJavaTemplate? Tried with @Before of junit; does not seem to work, Constructor also does not do anything... Below is the example code I have tried out, the sysout does not come in the terminal
 
```
package some.template;

import cucumber.api.CucumberOptions;
import cucumber.api.junit.Cucumber;
import org.junit.Before;
import org.junit.runner.RunWith;

@RunWith(Cucumber.class)
@CucumberOptions(
    glue = "steps",
    features = {"target/parallel/features/[CUCABLE:FEATURE].feature"},
    plugin = {"json:target/cucumber-report/[CUCABLE:RUNNER].json"}
)
public class CucableJavaTemplate {

  @Before
  public void before() {
    System.out.println("Something is inside here");
  }
}
```
How do I initialize all the required stuff so that while the compiler reaches my step definition I do not run into NullPointers?

PS: I am of the understanding that each since each runner would run a single scenario it would have run in it's isolated jvm. Please correct me if I am wrong.

**Comment by laxersaz** [comment]
In its default setting, each runner runs a single scenario in an isolated JVM (depending on the Failsafe settings). The runners themselves are just normal runner classes that behave the same as as your "normal" runners. Since this highly depends on your test framework and is unrelated to Cucable, I unfortunately cannot help you with that.

**Comment by VinnieM** [comment]
Thank you for the response. However I do have a question. I am trying to run the example provided with the project (The code mentioned above). If they are normal classes why do you think the sysout is not getting printed? I can share the code if required.

**Comment by laxersaz** [comment]
JUnit `@Before` annotations don't work in Cucumber. The way to go would be `cucumber.api.java.Before`. However, these cannot be defined inside the runner class (as clearly stated in the error message):
```
Classes annotated with @RunWith(Cucumber.class) must not define any
Step Definition or Hook methods. Their sole purpose is to serve as
an entry point for JUnit. Step Definitions and Hooks should be defined
in their own classes. This allows them to be reused across features. 
```

**Comment by VinnieM** [comment]
Yep, I got that as well...Do you have any suggestions? I was able to use the @BeforeClass inside the runner, trying with that.

PS: Do you think initializing stuff inside the Runner is a poor design?

**Comment by laxersaz** [comment]
Please understand that this is only a place to discuss Cucable issues and not give general advice.

**Comment by VinnieM** [comment]
Got it, thanks for your help.
