### ISSUE TITLE
Issue in identifying feature file/directory

### ISSUE THREAD

**Issue by tusharkhoche** [trivago/cucable-plugin#112]
Hi @laxersaz , I did all that which is required for the plugin to work. I am getting error in POM that resources/features/searchflights is not a feature file or a directory. The path is correct as you can see in attached screenshot.

![image](https://user-images.githubusercontent.com/19679029/56652775-c90ba300-66a9-11e9-86be-e1addaf5ce85.png)

![image](https://user-images.githubusercontent.com/19679029/56652795-d45ece80-66a9-11e9-8c01-4f590f723ded.png)

**Here is my pom.xml**
Please do let me know if I am missing something. Thanks

`<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.epam</groupId>
	<artifactId>cleartrip</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>cleartrip</name>
	<url>http://maven.apache.org</url>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<maven.failsafe.plugin.version>3.0.0-M3</maven.failsafe.plugin.version>
		<maven.build.helper.plugin.version>3.0.0</maven.build.helper.plugin.version>
		<maven.compiler.plugin.version>3.8.0</maven.compiler.plugin.version>

		<generated.runner.directory>${project.build.directory}/parallel/runners</generated.runner.directory>
		<generated.feature.directory>${project.build.directory}/parallel/features</generated.feature.directory>
	</properties>
	<repositories>
		<repository>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
			<id>bintray-epam-reportportal</id>
			<name>bintray</name>
			<url>http://dl.bintray.com/epam/reportportal</url>
		</repository>
	</repositories>

	<build>
		<plugins>
			<plugin>
				<groupId>org.sonarsource.scanner.maven</groupId>
				<artifactId>sonar-maven-plugin</artifactId>
				<version>3.6.0.1398</version>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>8</source>
					<target>8</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>com.trivago.rta</groupId>
				<artifactId>cucable-plugin</artifactId>
				<version>1.5.0</version>
				<executions>
					<execution>
						<id>generate-test-resources</id>
						<phase>generate-test-resources</phase>
						<goals>
							<goal>parallel</goal>
						</goals>
						<configuration>
							
							<sourceRunnerTemplateFile>src/test/java/com/epam/cleartrip/cucable.java
							</sourceRunnerTemplateFile>
							

							
							<sourceFeatures>resources/features/searchflights</sourceFeatures>

							
							

							
							

							<generatedFeatureDirectory>${generated.feature.directory}</generatedFeatureDirectory>
							<generatedRunnerDirectory>${generated.runner.directory}</generatedRunnerDirectory>

							
							
							
							

							
							
							
							
							

							
							
							
							

							
							

							
							

							
							
							
							
							
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>build-helper-maven-plugin</artifactId>
				<version>3.0.0</version>
				<executions>
					<execution>
						<id>add-test-source</id>
						<phase>generate-test-sources</phase>
						<goals>
							<goal>add-test-source</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<sources>
						<source>${generated.runner.directory}</source>
					</sources>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-failsafe-plugin</artifactId>
				<version>3.0.0-M3</version>
				<executions>
					<execution>
						<id>Run parallel tests</id>
						<phase>integration-test</phase>
						<goals>
							<goal>integration-test</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<forkCount>2</forkCount>
					<testFailureIgnore>true</testFailureIgnore>
				</configuration>
			</plugin>
		</plugins>

		<pluginManagement>
			<plugins>
				
				<plugin>
					<groupId>org.eclipse.m2e</groupId>
					<artifactId>lifecycle-mapping</artifactId>
					<version>1.0.0</version>
					<configuration>
						<lifecycleMappingMetadata>
							<pluginExecutions>
								<pluginExecution>
									<pluginExecutionFilter>
										<groupId>
											com.trivago.rta
										</groupId>
										<artifactId>
											cucable-plugin
										</artifactId>
										<versionRange>
											[1.5.1,)
										</versionRange>
										<goals>
											<goal>parallel</goal>
										</goals>
									</pluginExecutionFilter>
									<action>
										<execute></execute>
									</action>
								</pluginExecution>
								<pluginExecution>
									<pluginExecutionFilter>
										<groupId>
											com.trivago.rta
										</groupId>
										<artifactId>
											cucable-plugin
										</artifactId>
										<versionRange>
											[1.5.0,)
										</versionRange>
										<goals>
											<goal>parallel</goal>
										</goals>
									</pluginExecutionFilter>
									<action>
										<execute></execute>
									</action>
								</pluginExecution>
							</pluginExecutions>
						</lifecycleMappingMetadata>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
	<dependencies>
		<dependency>
			<groupId>com.epam.reportportal</groupId>
			<artifactId>agent-java-cucumber4</artifactId>
			<version>4.0.0</version>
		</dependency>
		<dependency>
			<groupId>com.epam.reportportal</groupId>
			<artifactId>agent-java-junit</artifactId>
			<version>4.1.0</version>
		</dependency>
		<dependency>
			<groupId>com.epam.reportportal</groupId>
			<artifactId>logger-java-log4j</artifactId>
			<version>4.0.1</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>1.7.25</version>
		</dependency>
		
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>gherkin</artifactId>
			<version>2.12.2</version>
			<scope>provided</scope>
		</dependency>
		
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
		</dependency>
		
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-server</artifactId>
			<version>3.14.0</version>
		</dependency>
		
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-core</artifactId>
			<version>2.11.1</version>
		</dependency>
		
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-api</artifactId>
			<version>2.11.1</version>
		</dependency>
		
		<dependency>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-compiler-plugin</artifactId>
			<version>3.8.0</version>
		</dependency>
		
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-core</artifactId>
			<version>4.2.3</version>
		</dependency>
		
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-junit</artifactId>
			<version>4.2.3</version>
		</dependency>
		
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-java</artifactId>
			<version>4.2.3</version>
		</dependency>
		
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-jvm</artifactId>
			<version>4.2.3</version>
			<type>pom</type>
		</dependency>
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-picocontainer</artifactId>
			<version>4.2.3</version>
		</dependency>
		
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>datatable</artifactId>
			<version>1.1.12</version>
		</dependency>
		
		<dependency>
			<groupId>com.aventstack</groupId>
			<artifactId>extentreports</artifactId>
			<version>4.0.9</version>
		</dependency>
	</dependencies>
</project>`

**Comment by laxersaz** [comment]
Hi, I just tried it with a similar setup using the example project and it works correctly.
Did you try taking the example project and modifying it step by step to match your desired setup?
At first glance I cannot see any error.

**Comment by tusharkhoche** [comment]
Yeah your example project works correctly now (https://github.com/trivago/cucable-plugin/issues/111). I have just copy pasted POM settings from the example project.
