### ISSUE TITLE
mvn clean verify runs successfully but doesn’t create any files.

### ISSUE THREAD

**Issue by murali4624** [trivago/cucable-plugin#114]
I cloned the cucable plugin project and navigated to example project(cucable-test-project). 
Executing mvn clean verify does not create any feature files or additional runner files.

However the build says Success.

Only change in the Pom after cloning is - added pluginManagement tag to avoid the error in eclipse.

![image](https://user-images.githubusercontent.com/44981358/58569300-7a4aaf00-81fb-11e9-8fcc-9c5047f9de92.jpg)

Please let me know how I can resolve this. I apologize for not been able to share the pom from my work laptop.

**Comment by gazler22** [comment]
There is some issue with the `PluginManagement` tag with the `m2e `plugin in eclipse. Looking here might help: 

https://stackoverflow.com/questions/6352208/how-to-solve-plugin-execution-not-covered-by-lifecycle-configuration-for-sprin

This is not a Cucable specific issue.

As a WA, you can remove Cucable plugin from the `PluginManagement` tag and use the project that way. The lifecycle error that you get with eclipse only affects m2e and nothing else. The project should still work fine as is.

**Comment by laxersaz** [comment]
@murali4624 did this work? If so, please close the issue.

**Comment by murali4624** [comment]
Thanks @gazler22 . It worked.
Thanks @laxersaz for a great plugin!
