### ISSUE TITLE
Gradle implementation

### ISSUE THREAD

**Issue by DeChrish** [trivago/cucable-plugin#115]
**Is your feature request related to a problem? Please describe.**
This feature request is not related to problem.

**Describe the solution you'd like**
Currently we are using maven build, Migrating to gradle.

**Describe alternatives you've considered**
We don't have alternative  

**Additional context**

**Comment by laxersaz** [comment]
I don't have much experience with gradle. So whoever wants to tackle this - feel free :-)

**Comment by AdamPike** [comment]
@DeChrish You can't directly use a Maven plugin in Gradle, you'd need to port across. Here's the documented on steps for migrating a project from Maven to Gradle: https://docs.gradle.org/current/userguide/migrating_from_maven.html

**Comment by laxersaz** [comment]
We are currently in the process of working on the gradle implementation of Cluecumber. If this is successful, I will also do this for Cucable.

**Comment by laxersaz** [comment]
There will be a bugfix release 1.6.0 of Cucable this year but the gradle version is not planned yet.

**Comment by laxersaz** [comment]
Gradle version was declined as this project will be phased out in the near future.
