### ISSUE TITLE
parallelization mode "features" with TAGS

### ISSUE THREAD

**Issue by DeChrish** [trivago/cucable-plugin#117]
**Is your feature request related to a problem? Please describe.**
I have multiple feature files, and need to execute @regression tag, Most features used same test data, so we cannot run by scenarios;

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by laxersaz** [comment]
Sorry I don't understand your situation. What do you mean with "Most features used same test data" - how is this defined? And why can't you use scenarios?
Maybe you can post an example feature file.

**Comment by DeChrish** [comment]
@laxersaz We are doing data setup before each scenario and will update the data in between steps. And we are using the same data in multiple scenarios. So if we run in parallel we might get into data issues. So we grouped the scenarios in a feature file so that we can run in test in parallel by feature, so when we run in parallel we will not encounter data issues.

Now we need to split parallel by Feature but need to include @tag also.

Hope i explained the use case?

**Comment by laxersaz** [comment]
You can just filter for tags in your Cucumber runner while running the generated features.

**Comment by laxersaz** [comment]
Closed due to no reaction.
