### ISSUE TITLE
Can we use surefire plugin?  We are using a open source framework, where surefire plugin is used to execute the test.

### ISSUE THREAD

**Issue by DeChrish** [trivago/cucable-plugin#118]
**Is your feature request related to a problem? Please describe.**

Currently when we split the features, the class file is created without extension.

**Describe the solution you'd like**
When we split, plugin should create runner with extension in the folder

<img width="473" alt="CurrentState" src="https://user-images.githubusercontent.com/6211294/59816645-c4dabb00-92d1-11e9-9661-3ed7c20db749.png">
<img width="387" alt="Expected" src="https://user-images.githubusercontent.com/6211294/59816652-c7d5ab80-92d1-11e9-8fc6-e420eb882a0f.png">

**Comment by laxersaz** [comment]
Hi! I don't understand what you mean. The java classes are never shown with a `.java` extension in IntelliJ. Also, this description does not really match the title of this issue. Can you share some more details to clarify this?

**Comment by laxersaz** [comment]
Closed due to no reaction.
