### ISSUE TITLE
When you run in parallel using cucable, will it run in separate threads or separate jvm process ?

### ISSUE THREAD

**Issue by murali4624** [trivago/cucable-plugin#119]
Note: This is a question and not a bug/feature.

I am using cucable to generate separate scenario files and runner files and running them in parallel using testng. I would like to know when you run in parallel using cucable, will it run in separate threads or separate jvm process (using maven failsafe)? 

My goal is to share data (confit data) between threads while running in parallel. What will be the best option? Should I simply use a static variable ?

**Comment by laxersaz** [comment]
This is unrelated to Cucable as it does not run the tests. When you use failsave you can configure it to run in threads inside the same jvm or completely separate jvms.

**Comment by murali4624** [comment]
Thanks @laxersaz . Can you please point me out on How I can modify it to execute on threads in one jvm?

**Comment by laxersaz** [comment]
Please check the failsafe documentation for this.

**Comment by murali4624** [comment]
Thank you. Will do.

**Comment by murali4624** [comment]
Thank you. Will do.
