### ISSUE TITLE
Google Guice @Inject issue in 0.0.6

### ISSUE THREAD

**Issue by gvaghjiani** [trivago/cucable-plugin#12]
With the latest 0.0.6 version a simple 'mvn clean verify' fails with the following error:

> 1) Could not find a suitable constructor in com.trivago.rta.CucablePlugin. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at com.trivago.rta.CucablePlugin.class(Unknown Source)
  while locating com.trivago.rta.CucablePlugin
  at ClassRealm[plugin>com.trivago.rta:cucable-plugin:0.0.6, parent: sun.misc.Launcher$AppClassLoader@55f96302]
  while locating org.apache.maven.plugin.Mojo annotated with @com.google.inject.name.Named(value=com.trivago.rta:cucable-plugin:0.0.6:parallel)
1 error
        at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:974)
        at com.google.inject.Scopes$1$1.get(Scopes.java:59)
        at org.sonatype.guice.bean.locators.LazyBeanEntry.getValue(LazyBeanEntry.java:83)
        at org.sonatype.guice.plexus.locators.LazyPlexusBean.getValue(LazyPlexusBean.java:49)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:253)
        ... 23 more

This does not happen in 0.0.5

I have created a new project with an empty test runner to rule out injection library conflicts and I get the same problem.

Here is my pom:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>mygroupid</groupId>
    <artifactId>myartifact</artifactId>
    <version>1.0-SNAPSHOT</version>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <maven.failsafe.plugin.version>2.20</maven.failsafe.plugin.version>
    </properties>

    <dependencies>

    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>com.trivago.rta</groupId>
                <artifactId>cucable-plugin</artifactId>
                <version>0.0.6</version>
                <executions>
                    <execution>
                        <id>generate-test-resources</id>
                        <phase>generate-test-resources</phase>
                        <goals>
                            <goal>parallel</goal>
                        </goals>
                        <configuration>
                            <sourceRunnerTemplateFile>src/test/resources/parallel/cucable.template</sourceRunnerTemplateFile>
                            <sourceFeatures>src/test/resources/features</sourceFeatures>
                            <generatedFeatureDirectory>src/test/resources/parallel/features</generatedFeatureDirectory>
                            <generatedRunnerDirectory>src/test/java/parallel</generatedRunnerDirectory>
                            <numberOfTestRuns>1</numberOfTestRuns>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>${maven.failsafe.plugin.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <includes>
                        <include>**/RunCukes.*</include>
                    </includes>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```

Java version:

> java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Maven version:

> Apache Maven 3.0.4 (r1232337; 2012-01-17 08:44:56+0000)

**Comment by laxersaz** [comment]
I will investigate this. Thanks for reporting!

**Comment by laxersaz** [comment]
@gvaghjiani I just created a simple test project and everything works as expected: 
https://github.com/laxersaz/cucable-test-project/

Can you try this one as well?

**Comment by laxersaz** [comment]
It might be an issue with your old Maven version (it is almost 6 years old). I am using 3.3.9 here.

**Comment by gvaghjiani** [comment]
Thank you - I upgraded maven and it's working
