### ISSUE TITLE
How to glue two different packages ?

### ISSUE THREAD

**Issue by Naumansh** [trivago/cucable-plugin#122]
I have two different step definition packages. I am trying to glue them as below:
@RunWith(Cucumber.class)
@CucumberOptions(
        glue = {"automation/bots/bdd,sba/sbir/steps"},
        features = {"target/parallel/features/[CUCABLE:FEATURE].feature"},
        plugin = {"pretty", "html:target/Automation-Report/Cucumber-report","json:target/cucumber-report/cucumber.json"},
        monochrome = true

)
public class CustomCreator {

}

**Error**

sage: <main class> [options] The XML suite files to run
  Options:
    -configfailurepolicy
      Configuration failure policy (skip or continue)
    -d
      Output directory
    -dataproviderthreadcount
      Number of threads to use when running data providers
    -excludegroups
      Comma-separated list of group names to  exclude
    -groups
      Comma-separated list of group names to be run
    -junit
      JUnit mode
      Default: false
    -listener
      List of .class files or list of class names implementing ITestListener 
      or ISuiteListener
    -methods
      Comma separated of test methods
      Default: []
    -methodselectors
      List of .class files or list of class names implementing IMethodSelector
    -mixed
      Mixed mode - autodetect the type of current test and run it with 
      appropriate runner
      Default: false
    -objectfactory
      List of .class files or list of class names implementing 
      ITestRunnerFactory 
    -parallel
      Parallel mode (methods, tests or classes)
      Possible Values: [tests, methods, classes, instances, none, true, false]
    -port
      The port
    -reporter
      Extended configuration for custom report listener
    -suitename
      Default name of test suite, if not specified in suite definition file or 
      source code
    -suitethreadpoolsize
      Size of the thread pool to use to run suites
      Default: 1
    -testclass
      The list of test classes
    -testjar
      A jar file containing the tests
    -testname
      Default name of test, if not specified in suitedefinition file or source 
      code 
    -testnames
      The list of test names to run
    -testrunfactory, -testRunFactory
      The factory used to create tests
    -threadcount
      Number of threads to use when running tests in parallel
    -usedefaultlisteners
      Whether to use the default listeners
      Default: true
    -log, -verbose
      Level of verbosity
    -xmlpathinjar
      The full path to the xml file inside the jar file (only valid if 
      -testjar was specified)

PS: Both these packages work fine when placed as single.

**Comment by laxersaz** [comment]
Hi! This is unrelated to Cucable as it just generates the runner classes from your template. Please check the according Cucumber documentation.
