### ISSUE TITLE
Overcounting of step usage in All Steps - Report

### ISSUE THREAD

**Issue by Naumansh** [trivago/cucable-plugin#129]
Under the "All Steps" tab of the report the "Step Summary Result Chart" y-axis is marked as "Number of Scenarios".  This would imply that it is showing how many scenarios a step is used in.  However, if a step is used multiple times in a scenario it is counted multiple times, leading to unexpectedly skewed data.  

Possible Solutions: 
   Each step should be counted once for each scenario
   The y-axis should be relabeled to "Number of Usages"

**Comment by laxersaz** [comment]
This is not a Cucable issue. Please open it in the Cluecumber repository.

**Comment by Naumansh** [comment]
Sorry about that. its my bad.
