### ISSUE TITLE
Cucable-Run into error with failsafe dependency upgrade

### ISSUE THREAD

**Issue by Srinivasaraor** [trivago/cucable-plugin#132]
**Describe the bug**
i have default(sequential) and Parallel(cucable) profiles configured in my maven project. when i upgrade failsafe dependency above 2.18 i am running into below error with parallel profile 
**:((The filename, directory name, or volume label syntax is incorrect)**).

I am not sure if it is some thing to do with cucable or my project structure , Please throw some light on this problem.
**To Reproduce**
1. Upgraded failsafe dependency to 3.0.0-M3
2. Run the tests with cucable plugin 
3. See error

**Expected behavior**

**Attachments**
If applicable, add an attachment to help explain your problem.

**Additional context**

**Comment by laxersaz** [comment]
Sorry I am afraid I can't help with this as this is unrelated to Cucable. Actually, we also use Failsafe 3.0.0-M3 for parallel execution of the generated runners and features and don't have problems.
This is something that is definitely related to your project structure / settings.

**Comment by Srinivasaraor** [comment]
Thanks for quick response  (Closing this issue (Not related to cucable)
