### ISSUE TITLE
Disallow property combination scenarioNames and parallelizationMode = features

### ISSUE THREAD

**Issue by josepj** [trivago/cucable-plugin#133]
The option `scenarioNames` will not work as expected when `parallelizationMode` is set to `features`. This is especially true when the feature file has scenario outlines. 

Would adding a check to disallow property combination `scenarioNames` and `parallelizationMode = features` suffice? I cannot think of a scenario where this combination is absolutely required that `scenarioNames` and `parallelizationMode = scenarios` cannot handle.

**Comment by laxersaz** [comment]
That makes sense :-)

**Comment by josepj** [comment]
@laxersaz, the text of the exception has `In parallelizationMode = FEATURE, you cannot specify xyz`.  Would it be better to say `In parallelizationMode = features`, as a user will specify `features` or `scenarios`?

**Comment by laxersaz** [comment]
Yes that's true!

**Comment by josepj** [comment]
Thanks @laxersaz. I have updated the PR.
