### ISSUE TITLE
scenarioNames will fail when a feature file has Example: in place of Scenario:

### ISSUE THREAD

**Issue by josepj** [trivago/cucable-plugin#138]
Reference - [cucumber.io > Example](https://cucumber.io/docs/gherkin/reference/#example)
```    
The keyword Scenario is a synonym of the keyword Example.
```

**Comment by josepj** [comment]
Looks like `Example` keyword was introduced in [Gherkin v6.0.13](https://github.com/cucumber/cucumber/blob/master/gherkin/CHANGELOG.md#6013---2018-09-25). Cucable is using 5.1.0.

**Comment by laxersaz** [comment]
I created the issue #139 for this. Thanks!
