### ISSUE TITLE
Feature: Make cucable.template a .java file instead of text file

### ISSUE THREAD

**Issue by jedi-tester** [trivago/cucable-plugin#14]
It would be nice to have the runner template as a .java file instead of text. This would make editing/configuring your runners a bit easier.

Not sure if it's possible though. Haven't investigated this yet myself due to lack of time.

**Comment by laxersaz** [comment]
Interesting idea. It might be possible and I will investigate this for sure.

**Comment by laxersaz** [comment]
@jedi-tester , I have not forgotten about this. The next release will include the other 4 features in the backlog but after that I hopefully can tackle this one.

**Comment by laxersaz** [comment]
@jedi-tester this is now supported in version 0.1.9 which will be available on maven central today.
