### ISSUE TITLE
Tagging Outlines results in too many tags in feautres

### ISSUE THREAD

**Issue by boris779** [trivago/cucable-plugin#145]
**Describe the bug**
When using Scenario Outlines (Szenariogrundriss) the generated features has the tags multiple times

**To Reproduce**
Example Feature:

\# language: de
\# encoding: utf-8

\@ smoke \@ mobile \@ Antrag
Funktionalität: Antrage ausfüllen

  \@ resetData
  Szenariogrundriss: Öffnen von Anträgen
    Angenommen die Startseite ist als "Max" geladen
    Dann sollte der Antrag "\<antragsnr\>" den Status "\<status\>" haben

    Beispiele:
      | antragsnr             | status           |
      | AZ 1                  | Storniert        |
      | AZ 2                  | Eingelangt       |
      | AZ 3                  | Unvollständig    |
      | AZ 4                  | Genehmigt        |
      | AZ 5                  | Abgelehnt        |

	  
This will result in a generated feature of:

	  
\@ smoke
\@ mobile
\@ Antrag
Funktionalität: Anträge ausfüllen

\@ resetData
\@ smoke
\@ mobile
\@ Antrag
\@ smoke
\@ mobile
\@ Antrag
\@ smoke
\@ mobile
\@ Antrag
\@ smoke
\@ mobile
\@ Antrag
\@ smoke
\@ mobile
\@ Antrag
Szenario: [Öffnen von Anträgen
Angenommen die Startseite ist als "Max" geladen
Dann sollte der Antrag "AZ 5" den Status "Abgelehnt" haben	

**Expected behavior**
Every feature has the tags ONCE. The reports are a kind of full with tags

I've added blanks between @ and the tag name to prevent GitHub will link that to a GitHub user (

**Comment by laxersaz** [comment]
Oh, this sounds like a bug. I will need to check this. Thanks for reporting.

**Comment by laxersaz** [comment]
Fixing for next release 1.6.0
