### ISSUE TITLE
Ability to run selected feature file for parallel execution

### ISSUE THREAD

**Issue by sunnysachdeva99** [trivago/cucable-plugin#152]
**Describe the bug**
Currently, when  parallelizationMode = features, we need to provide a path to directory which has all the features. But there is no way where, one can pass selected feature files at run time to run in parallel

**Comment by laxersaz** [comment]
You can specify selected feature files as well. This is also stated in the documentation:

https://github.com/trivago/cucable-plugin#sourcefeatures

There it says that you can either specify a path to a directory or one or multiple feature files like so

```
<sourceFeatures>
    src/test/resources/features/sometests,
    src/test/resources/features/MyFeature.feature:8:15
</sourceFeatures>
```

**Comment by sunnysachdeva99** [comment]
Thanks @laxersaz . I read that in documentation but how do I provide these feature file names from command prompt (in mvn command)

**Comment by laxersaz** [comment]
Hello again, you can achieve that like this (in the Cluecumber Report Plugin documentation):

https://github.com/trivago/cluecumber-report-plugin#passing-properties-via-command-line

This way, you can pass properties from the command prompt.

**Comment by laxersaz** [comment]
Closing it for now.
