### ISSUE TITLE
compilation error is thrown when the feature name starts with a number

### ISSUE THREAD

**Issue by prabhus06** [trivago/cucable-plugin#156]
**Describe the bug**
When the feature file name is starting with a number then when the runner is generated it generated with the class name starting with number and hence throws compilation error.

**To Reproduce**
1. Create a scenario with... a feature file name starting with number
2. Run Cucable
3. See error

java: illegal underscore

**Comment by laxersaz** [comment]
Hello @prabhus06 ,
thanks for reporting this!
