### ISSUE TITLE
[Question] Can we override GLUE

### ISSUE THREAD

**Issue by DeChrish** [trivago/cucable-plugin#157]
We are sharing the cucable plugin via library, team has different glue methods. How they can use the common cucable template and use their own glue steps.

**Comment by laxersaz** [comment]
You can use custom placeholders for this:
https://github.com/trivago/cucable-plugin#custom-template-placeholders---cucablecustomxxx

**Comment by laxersaz** [comment]
Did this answer your question, @DeChrish ?

**Comment by laxersaz** [comment]
Closed due to no reaction.
