### ISSUE TITLE
Example Missing for Junit 5 & Cucumber 5.5

### ISSUE THREAD

**Issue by boris779** [trivago/cucable-plugin#159]
Run a cucumber test with cucable and Junit 5

What I did:
1. Updated the dependencies
2. Edited the Template
3. run a mvn clean verify
4. Got Errors that my template has no [CUCABLE:FEATURE]

Used Dependecies:
junit-jupiter-api
cucumber-junit-platform-engine
cucumber-java
cucumber-java8

But with Junit 5 and cucumber 5.7.0 there are no cucumber Options

This is maybe only a documentation bug, could you provide also a junit 5.7.0 / Cucumber 5.5Example?

**Comment by laxersaz** [comment]
`CucumberOptions` still exist in Cucumber 5.7.0 as far as I can see from the changelog: https://github.com/cucumber/cucumber-jvm/blob/master/CHANGELOG.md#570-2020-05-01.
Also, the message that `[CUCABLE:FEATURE]` is not included in the template is independent Cucumber and JUnit as Cucable runs before.

Could you share a minimal project so I can see what exactly you did?

**Comment by boris779** [comment]
Sorry for the late response. 
I think the problem was that for the CucumberOptions I had to import io.cucumber.junit.CucumberOptions and add the dependecy io.cucumber-junit

I think it works now.

**Comment by laxersaz** [comment]
Cool! If you have any more questions, just ping me!
