### ISSUE TITLE
Tests are running sequentially

### ISSUE THREAD

**Issue by Hanumanthap24** [trivago/cucable-plugin#162]
Hi,

I have couple of questions.
1.I am running my tests in using maven i.e mvn test -Dcucumber.options="--tags @US1"
.I can see 10 features and 10 TestRunner files getting generated.But my problem is that,my tests run sequentially,one after the other.Could you please let me know what all the factors control the parallel execution.My fork Count is 10.
2.When my test are run,
In the end will see a message like this.
java.lang.IllegalArgumentException: Not a file or directory: C:\MyProject\target\parallel\features\[CUCABLE:FEATURE].feature.
Could you please help

Thanks,
Hanumantha

**Comment by laxersaz** [comment]
Have you tried running the Cucable example project? if you run with `mvn test` you are not running with Failsafe but with Surefire. 
The error message also looks like your setup is wrong. Please create a small example so I can take a look.

**Comment by Hanumanthap24** [comment]
Could you please tell me how to run with failsafe?

**Comment by Naumansh** [comment]
@Hanumanthap24 try with mvn verify

**Comment by Hanumanthap24** [comment]
@Naumansh :Thanks mate.Tests are now running in parallel.
