### ISSUE TITLE
Cucable in Jenkins Pipeline

### ISSUE THREAD

**Issue by Hanumanthap24** [trivago/cucable-plugin#163]
Hi ,

I am able to execute my scripts parallely on my local machine.I created a groovy script and included following script in run step of my pipeline.
mvn verify -f pom.xml -Dgrid.run=true -Dbrowser="${Browser}" -Dgrid.hub.server="${EnvironmentToExecute}" -Dcucumber.options=". --tags ${ExecutingTag}'

I have couple of issues:
1.Scripts are not running in parallel when I execute through Jenkins.
2.Cucumber report is not generated.

Could you please help.

**Comment by Hanumanthap24** [comment]
Any update?

**Comment by laxersaz** [comment]
I cannot help here as I don't know how your project is set up. Just showing a script invocation gives no hints. Please create an example project and attach it to this task.
