### ISSUE TITLE
Feature files in folder

### ISSUE THREAD

**Issue by Hanumanthap24** [trivago/cucable-plugin#166]
Hi 
I have feature files in multiple folders such as 
src/test/resources/features/Sprint-1
src/test/resources/features/Sprint-2
src/test/resources/features/Sprint-3
src/test/resources/features/Sprint-4

and in my pom xml

                   <sourceFeatures>src/test/resources/features/sprint-1</sourceFeatures>
                    <sourceFeatures>src/test/resources/features/sprint-2</sourceFeatures>
                    <sourceFeatures>src/test/resources/features/sprint-3</sourceFeatures>
                    <sourceFeatures>src/test/resources/features/sprint-4</sourceFeatures>
When I run my test using the below command ,it does not pick the tests which is in one of the above folder.
mvn verify -Dcucumber.options="--tags @US1" -Dbrowser=chrome

But when I specify the correct folder src/test/resources/features/Sprint-1 my tests run properly.
could you please help.

**Comment by laxersaz** [comment]
Hello, why was this closed? Did you solve it?

**Comment by Hanumanthap24** [comment]
Nope.I thought it has but it isn't.Could you please help?Also ,the way I specified folder structure in pom.xml is correct?

**Comment by laxersaz** [comment]
This is not the right way to specify multiple folders. It is all described here: https://github.com/trivago/cucable-plugin#sourcefeatures

You can either specify the root folder of them all like so
`<sourceFeatures>src/test/resources/features</sourceFeatures>`

or a comma separated list of directories llike this:
`<sourceFeatures>src/test/resources/features/sprint-1, src/test/resources/features/sprint-2</sourceFeatures>`

**Comment by Hanumanthap24** [comment]
Got error message as                    
    src/test/resources/features/sprint-16,
                        src/test/resources/features/sprint-17,
                        src/test/resources/features/sprint-18,
                        src/test/resources/features/sprint-19,
                        src/test/resources/features/sprint-20,
                        src/test/resources/features/sprint-21,
                        src/test/resources/features/sprint-22,
                        src/test/resources/features/sprint-23,
                        src/test/resources/features/sprint-24 is not a feature file or a directory.

and when specify 
 <sourceFeatures>src/test/resources/features</sourceFeatures>

got error message,
Failed to execute goal com.trivago.rta:cucable-plugin:1.1.0:parallel (generate-test-resources) on project Projects: Execution generate-test-resources of goal com.trivago.rta:cu
cable-plugin:1.1.0:parallel failed: 21 -> [Help 1]

**Comment by Hanumanthap24** [comment]
Any update?

**Comment by laxersaz** [comment]
I am currently on vacation so please don't expect an answer before next week. Thanks.

**Comment by laxersaz** [comment]
Please note that the current Cucable version is 1.7.2, not 1.1.0 that you use.

**Comment by laxersaz** [comment]
Have you tried it with the current version?

**Comment by laxersaz** [comment]
Closed due to no reaction.
