### ISSUE TITLE
parallelizationMode tag error

### ISSUE THREAD

**Issue by Hanumanthap24** [trivago/cucable-plugin#167]
Hi,
I have a problem that,when I use parallelizationMode tag as shown below,the xml throws some error saying the tag is not allowed here.Is there something wrong below?
  
[xml2.txt](https://github.com/trivago/cucable-plugin/files/4994242/xml2.txt)

**Comment by laxersaz** [comment]
Are you using the newest Cucable version?

**Comment by laxersaz** [comment]
No reaction.
