### ISSUE TITLE
Cucumber Tags and and Or

### ISSUE THREAD

**Issue by Hanumanthap24** [trivago/cucable-plugin#168]
Hi ,

I have a scenario like this.

My Feature file:
@US1
Feature:My feature

Scenario outline:Tc1
Given
When 
Then

@Env
Examples:

@Env2
Examples:

@Env3:
Examples

And When i run my test cases like

mvn verify -Dtags="@US1 and @Env"

This will run all the test cases under the folder in which my feature file resides and not this feature file alone.
Could you tell me if this is not the correct way using and & Or.

**Comment by laxersaz** [comment]
Hello, "tags" is not a Cucable option.
It is all described in the documentation:
https://github.com/trivago/cucable-plugin#includescenariotags

**Comment by Hanumanthap24** [comment]
[Xml.txt](https://github.com/trivago/cucable-plugin/files/5074440/Xml.txt)

Please find my xml attached.

I have included my tags in XML..When i run my test cases 
mvn clean verify -U -s settings.xml DrunParallelTests="true"

,in the logs it says.

[INFO] Cucable created 0 separate feature files and 0 runners.

If I run with only one tag like @US1,my test runs  all the test cases in the feature file.

What is the mistake here?

**Comment by laxersaz** [comment]
ˋ (@US1 and @env) and not @Env2ˋ says: run scenarios that have both us1 and env tags and not env2. Do you have scenarios that match this?

**Comment by Hanumanthap24** [comment]
Yes.As you see my in the first question I asked,My feature file tag name is @us1,and parameters are @env and @env2..
I am interested in executing all test cases in feature file with @env parameters(Examples).

**Comment by laxersaz** [comment]
Hi again, alright, I will investigate this. Maybe you found a bug there :-)

**Comment by laxersaz** [comment]
Yes it seems you did find a bug. I will try to fix it for the next release.

**Comment by Hanumanthap24** [comment]
When can we have this feature?Just need approx date.

**Comment by laxersaz** [comment]
I merged and released this 2 weeks ago (see above).
