### ISSUE TITLE
Generate runners and features in maven target

### ISSUE THREAD

**Issue by laxersaz** [trivago/cucable-plugin#17]
http://www.mojohaus.org/build-helper-maven-plugin/usage.html

**Comment by amaravathi** [comment]
correct me if I am wrong, either way directories are configurable , so we can use  some thing like <generatedFeatureDirectory>${project.build.directory}/parallel/features</generatedFeatureDirectory>   and                           <generatedRunnerDirectory>${project.build.directory}/parallel</generatedRunnerDirectory> and files will be in target folder

**Comment by laxersaz** [comment]
That's true but they won't be considered test sources. And since the runners have to be compiled it is not that easy. If you get it to work like you said I would be happy if you let me know so I can add it to the documentation.

**Comment by amaravathi** [comment]
Thank you laxersaz, as you rightly said those files cant be part of sources to get compiled .

Considering that in mind, have tweaked pom file to get test-sources comiple, and make .classes avaialble to run the test cases .

And here is my cucable.template and plugin details 
cucable.template 

@RunWith(Cucumber.class)
@CucumberOptions(
    monochrome = false,
    features = {"target/parallel/features/[FEATURE_FILE_NAME].feature"},
    format = {"json:target/cucumber-report/[FEATURE_FILE_NAME].json"},
    strict = false,
    dryRun = false,
    glue={"com.test.demostore.stepdefinition"},
    tags= {"@SmokeTest"}
)
public class [FEATURE_FILE_NAME] {
}


          <plugins>
           <plugin>
                <groupId>com.trivago.rta</groupId>
                <artifactId>cucable-plugin</artifactId>
                <version>0.0.9</version>
                <executions>
                    <execution>
                        <id>parallel</id>
                        <phase>generate-test-resources</phase>
                        <goals>
                            <goal>parallel</goal>
                        </goals>
                        <configuration>
                            <sourceRunnerTemplateFile>src/test/resources/parallel/cucable.template
                            </sourceRunnerTemplateFile>

                             
                             <sourceFeatures>src/test/resources/features</sourceFeatures> 

                            
                            

                            
                            

                            <generatedFeatureDirectory>${project.build.directory}/parallel/features</generatedFeatureDirectory>

                            <generatedRunnerDirectory>${project.build.directory}/parallel/runners</generatedRunnerDirectory>
                            <numberOfTestRuns>1</numberOfTestRuns>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
		        <groupId>org.codehaus.mojo</groupId>
		        <artifactId>build-helper-maven-plugin</artifactId>
		        <version>3.0.0</version>
		        <executions>
		          <execution>
		            <id>add-test-source</id>
		            <phase>generate-test-sources</phase>
		            <goals>
		              <goal>add-test-source</goal>
		            </goals>
		            <configuration>
		              <sources>
		                <source>${project.build.directory}/parallel/runners</source>		                
		              </sources>
		            </configuration>
		          </execution>
		        </executions>
      		</plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>                
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                        </goals>
                        <configuration>
                            <forkCount>2</forkCount>		                    
                        </configuration>
                    </execution>
                </executions>
            </plugin>
     <plugins>

**Comment by laxersaz** [comment]
That's cool, @amaravathi ! Thanks a lot for your detailed post. I will try that for sure and think about a good way to integrate it into Cucable if possible.

**Comment by laxersaz** [comment]
This will be moved to the main README.md file for the next version 0.1.7

**Comment by laxersaz** [comment]
I rewrote the readme file and included the description on how to generate features and runners in Maven target. Thanks again for your help!

**Comment by jaydeepqa** [comment]
I recently came across Cucable plugin and it works great for me, but I am facing one problem, that is how to attach screenshot in the report against any particular step.
