### ISSUE TITLE
Parse feature error

### ISSUE THREAD

**Issue by Danphillipz** [trivago/cucable-plugin#173]
Hi there, when running a maven build I am seeing the below error for 'could not parse feature'.
However, the project has hundreds of features and the error messages produced by cucable do not indicate exactly which feature file is causing the issue, so trying to identify the feature with the issue is proving very difficult

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  56.239 s
[INFO] Finished at: 2020-11-25T15:17:37Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.trivago.rta:cucable-plugin:1.8.0:parallel (generate-test-resources) on project cds-e2e-automation-main: Could not parse feature: Parser errors:
[ERROR] (208:7): inconsistent cell count within the table
[ERROR] (429:7): inconsistent cell count within the table
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by laxersaz** [comment]
Thanks for reporting this!

**Comment by laxersaz** [comment]
Fix in progress...

**Comment by Danphillipz** [comment]
@laxersaz That's great, thankyou very much

**Comment by laxersaz** [comment]
Done in 1.9.0 - release will happen during the next 30 minutes.
