### ISSUE TITLE
I am new to TestNG Framework, When executed code using TestNg, the cases are successfully executed but observed the below error. Please review and suggest why I am getting below error

### ISSUE THREAD

**Issue by Thiyagarajan9977** [trivago/cucable-plugin#174]
[TestNG] Running:
  C:\Users\Admin\AppData\Local\Temp\testng-eclipse-589218627\testng-customsuite.xml

Before Class
Before Method
Test1
After Method
Before Method
Test2
After Method
Before Method
Test3
After Method
after Class
[Utils] Attempting to create C:\Users\Admin\eclipse-workspace\SeleniumClass\TestNG\test-output\Default suite\Default test.xml
[Utils]   Directory C:\Users\Admin\eclipse-workspace\SeleniumClass\TestNG\test-output\Default suite exists: true
PASSED: test1
PASSED: test2
PASSED: test3

===============================================
    Default test
    Tests run: 3, Failures: 0, Skips: 0
===============================================

===============================================
Default suite
Total tests run: 3, Failures: 0, Skips: 0
===============================================

[TestNG] Reporter org.testng.reporters.JUnitReportReporter@3d8c7aca failed
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at org.testng.reporters.JUnitReportReporter.getNextConfiguration(JUnitReportReporter.java:220)
	at org.testng.reporters.JUnitReportReporter.generateReport(JUnitReportReporter.java:105)
	at org.testng.TestNG.generateReports(TestNG.java:1175)
	at org.testng.TestNG.run(TestNG.java:1102)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
[TestNG] Time taken by org.testng.reporters.XMLReporter@6bf256fa: 21 ms
[TestNG] Time taken by org.testng.reporters.EmailableReporter2@6aaa5eb0: 7 ms
[Utils] Attempting to create C:\Users\Admin\eclipse-workspace\SeleniumClass\TestNG\test-output\old\Default suite\toc.html
[Utils]   Directory C:\Users\Admin\eclipse-workspace\SeleniumClass\TestNG\test-output\old\Default suite exists: true
[Utils] Attempting to create C:\Users\Admin\eclipse-workspace\SeleniumClass\TestNG\test-output\old\Default suite\Default test.properties
[Utils]   Directory C:\Users\Admin\eclipse-workspace\SeleniumClass\TestNG\test-output\old\Default suite exists: true
[Utils] Attempting to create C:\Users\Admin\eclipse-workspace\SeleniumClass\TestNG\test-output\old\Default suite\index.html
[Utils]   Directory C:\Users\Admin\eclipse-workspace\SeleniumClass\TestNG\test-output\old\Default suite exists: true
[Utils] Attempting to create C:\Users\Admin\eclipse-workspace\SeleniumClass\TestNG\test-output\old\Default suite\main.html
[Utils]   Directory C:\Users\Admin\eclipse-workspace\SeleniumClass\TestNG\test-output\old\Default suite exists: true
[Utils] Attempting to create C:\Users\Admin\eclipse-workspace\SeleniumClass\TestNG\test-output\old\Default suite\groups.html
[Utils]   Directory C:\Users\Admin\eclipse-workspace\SeleniumClass\TestNG\test-output\old\Default suite exists: true
[Utils] Attempting to create C:\Users\Admin\eclipse-workspace\SeleniumClass\TestNG\test-output\old\Default suite\classes.html
[Utils]   Directory C:\Users\Admin\eclipse-workspace\SeleniumClass\TestNG\test-output\old\Default suite exists: true
[Utils] Attempting to create C:\Users\Admin\eclipse-workspace\SeleniumClass\TestNG\test-output\old\Default suite\reporter-output.html
[Utils]   Directory C:\Users\Admin\eclipse-workspace\SeleniumClass\TestNG\test-output\old\Default suite exists: true
[Utils] Attempting to create C:\Users\Admin\eclipse-workspace\SeleniumClass\TestNG\test-output\old\Default suite\methods-not-run.html
[Utils]   Directory C:\Users\Admin\eclipse-workspace\SeleniumClass\TestNG\test-output\old\Default suite exists: true
[Utils] Attempting to create C:\Users\Admin\eclipse-workspace\SeleniumClass\TestNG\test-output\old\Default suite\testng.xml.html
[Utils]   Directory C:\Users\Admin\eclipse-workspace\SeleniumClass\TestNG\test-output\old\Default suite exists: true
[Utils] Attempting to create C:\Users\Admin\eclipse-workspace\SeleniumClass\TestNG\test-output\old\index.html
[Utils]   Directory C:\Users\Admin\eclipse-workspace\SeleniumClass\TestNG\test-output\old exists: true
[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@2acf57e3: 47 ms
[TestNG] Time taken by org.testng.reporters.jq.Main@3796751b: 80 ms
[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 1 ms

**Comment by laxersaz** [comment]
Hello, this is unrelated to Cucable. How you run the tests after they are split up using Cucable is out of scope here so I unfortunately cannot help with this.
