### ISSUE TITLE
Let users specify tags when parallelizationMode='features'

### ISSUE THREAD

**Issue by rsshekhawat** [trivago/cucable-plugin#176]
**Is your feature request related to a problem? Please describe.**
I am not able to specify tags when parallelizationMode='features'. I am getting error message ', you cannot specify includeScenarioTags' when I try to do so. Please let users specify tags when parallelizationMode='features' also.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bischoffdev** [comment]
This is expected behavior which is stated in the documentation ([see here](https://github.com/trivago/cucable-plugin#parallelizationmode)):
`Note: For this mode to work, <sourceFeatures> must specify a directory. Also, includeScenarioTags cannot be used.`
