### ISSUE TITLE
Generate report even if maven build gets failed

### ISSUE THREAD

**Issue by onlyforcoding24** [trivago/cucable-plugin#178]
**Is your feature request related to a problem? Please describe.**
I am running my test cases in jenkins pipeline. currently, build is success even if test cases are failed because we have set the `<testFailureIgnore>true</testFailureIgnore>` in failsafe plugin. But my build should be failed if there are test failures.
if I set `<testFailureIgnore>false</testFailureIgnore>` then built is getting failed but report is not generated.

**Describe the solution you'd like**
I want report to get generated even if `<testFailureIgnore>true</testFailureIgnore>` is set in the failsafe plugin

**Describe alternatives you've considered**

**Additional context**

**Comment by bischoffdev** [comment]
This is Maven's expected behavior. Failing the build is out of scope for Cucable as it just generates features and runners and has no knowledge about the actual test results. Also, it is not responsible for creating test reports.
