### ISSUE TITLE
File not found error while attempting to use text file in the sourceFeatures tag

### ISSUE THREAD

**Issue by RathinaaDeepak** [trivago/cucable-plugin#182]
I am using cucable 1.9.0. I need to generate parallel runners for features specified in the text file. The files are located in src/test/resources/rerun.txt

This is my source feature tag

<sourceFeatures>@src/test/resources/rerun.txt<sourceFeatures>

Even If I just retain the folder alone (upto resources) , I am getting the same error.

I have not specified any include scenario tags. And the parallelizaion mode is scenarios.

ERROR:

trivago.rta.:cucable plug-in 1.9.0 parallel (generate-test-resources)  on project. File src/test/resources/rerun.txt could not be found.

**Comment by RathinaaDeepak** [comment]
And my cucumber version is 2.4.0

**Comment by bischoffdev** [comment]
Hello, can you provide a small sample project that demonstrates this?

**Comment by RathinaaDeepak** [comment]
@bischoffdev - Will update the details shortly

**Comment by RathinaaDeepak** [comment]
@bischoffdev 
While i am getting the example project ready, I have a quick question. Will the cucable plugin work with cucumber version as 2.4.0?

**Comment by bischoffdev** [comment]
The current Cucumber version is 7.12.0. 2.4.0 is five years old already. However, it should also work with this one.

**Comment by bischoffdev** [comment]
In general I would advise using the latest Cucable version (1.9.0). It is quite hard to know what's going on in your case without a small example project.
