### ISSUE TITLE
Option to specify directory path for text file used under sourceFeatures

### ISSUE THREAD

**Issue by RathinaaDeepak** [trivago/cucable-plugin#183]
**Is your feature request related to a problem? Please describe.**
To create cucable runners for features in a text file, the plugin requires us to specify the entire file path up to the text file name. 
Ex: @target/parallel/test-report/rerun.txt
**Describe the solution you'd like**
I would like to use only up to the directory path (Ex: @target/parallel/test-report). This is possible if the directory contains feature files. Does not work for text files.

**Describe alternatives you've considered**
There are situations where multiple text files are created and the names of the txt files are dynamic. We have to figure out a logic to identify the names of the dynamic text files and specify them individually under <sourceFeatures> tag which can be tedious.

**Comment by RathinaaDeepak** [comment]
@bischoffdev 
I ran mvn verify on the example project with the below value (directory path of the txt file) in the <sourceFeatures>. Got the below error

@src/test/resources/

![image](https://github.com/trivago/cucable-plugin/assets/82179098/de991cc6-4fb5-4ce4-9933-432a013cd8e0)

**Comment by RathinaaDeepak** [comment]
Thanks for the update @bischoffdev . During parallel execution, every cucuable runner can be made to generate a rerun file for failed tests. If there are 5 cucable runners, then there can be 5 rerun.txt files. Agree, this can be a edge case scenario, but would be really helpful if <sourceFeatures> can allow directory path. We would be able to rerun failed tests also using cucable.

**Comment by bischoffdev** [comment]
Implementation in progress...

**Comment by RathinaaDeepak** [comment]
Thanks you very much for the quick turn around @bischoffdev . 
Looking forward to work with the solution.

**Comment by bischoffdev** [comment]
Picking up development again after a break (I wasn't here)
