### ISSUE TITLE
Data tables with empty values are not processed correctly

### ISSUE THREAD

**Issue by gvaghjiani** [trivago/cucable-plugin#20]
Scenarios with data tables are not processed correctly if a cell in the table has a blank value 

If I have this table:

|header1|header2|header3|
|value1   |              |value3   |

Then the plugin processes this as:

|header1|header2|header3|
|value1   |             
|value3   |

**Comment by laxersaz** [comment]
Do you belong to QA? Your reports are really helpful. I will tackle this issue together with the other one you opened.

**Comment by laxersaz** [comment]
Fixed in version 0.0.8 - released today.
