### ISSUE TITLE
generatedFeatureDirectory and generatedRunnerDirectory does not get deleted

### ISSUE THREAD

**Issue by prasant-sethi** [trivago/cucable-plugin#27]
### Expected behavior
generatedFeatureDirectory and generatedRunnerDirectory should get deleted before every build
### Actual behavior
If I add/remove scenarios from the feature file, no change to the generated features or runners
### Additional details (Maven version, Java version, etc.)
java 8, maven 3.1.1

**Comment by laxersaz** [comment]
I will investigate this. Thanks for reporting.

**Comment by laxersaz** [comment]
@prasant-sethi, I tested it and the directories are recreated and wiped before every build. Some IDEs like IntelliJ do not update the directories real-time so you might see the old directory structure. If this issue persists for you there must be a configuration that alters this behavior.

Did you try using the Cucable test project (https://github.com/laxersaz/cucable-test-project) and do you see the same effect there?

**Comment by laxersaz** [comment]
There was no feedback. Closing issue.
