### ISSUE TITLE
Not able to generate runners

### ISSUE THREAD

**Issue by Subash85** [trivago/cucable-plugin#30]
I am trying to use the cucable  in my current project but the resources are not getting generated 
 could you help me with this . I have given the pom i am using 

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com</groupId>
	<artifactId>vPOL</artifactId>
	<version>1.0.0</version>
	<properties>
		<jre.level>1.8</jre.level>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		  <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <maven.failsafe.plugin.version>2.20.1</maven.failsafe.plugin.version>
        <junit.version>4.12</junit.version>
	</properties>
	<parent>
		<groupId>com.</groupId>
		<artifactId>addd</artifactId>
		<version>19.0</version>
	</parent>

	<dependencies>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-core</artifactId>
			<version>1.2.4</version>
		</dependency>

		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-testng</artifactId>
			<version>1.2.4</version>
		</dependency>

		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-java</artifactId>
			<version>1.2.4</version>
		</dependency>

		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-junit</artifactId>
			<version>1.2.4</version>
		</dependency>

		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>3.14</version>
		</dependency>

		<dependency>
		<groupId>org.apache.poi</groupId>
		<artifactId>poi-ooxml</artifactId>
		<version>3.14</version>
	</dependency>

		<dependency>
			<groupId>jexcelapi</groupId>
			<artifactId>jxl</artifactId>
			<version>2.4.2</version>
		</dependency>
		<dependency>
			<groupId>com.amex.autobot</groupId>
			<artifactId>autobot-cucumber</artifactId>
			<version>1.1.1</version>
		</dependency>

		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>2.47.1</version>
		</dependency>

		<dependency>
			<groupId>xml-apis</groupId>
			<artifactId>xml-apis</artifactId>
			<version>1.4.01</version>
		</dependency>

		<dependency>
			<groupId>net.masterthought</groupId>
			<artifactId>cucumber-reporting</artifactId>
			<version>0.6.0</version>
		</dependency>

	</dependencies>

	<profiles>
	
		
	 <profile>
        <id>parallel</id>
        <build>
            <plugins>
             <plugin>
          <artifactId>maven-resources-plugin</artifactId>
          <version>3.0.2</version>
        </plugin>
	          	<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>3.5</version>
					<configuration>
						<source>1.8</source>
						<target>1.8</target>
					</configuration>
				</plugin>
	          		
                <plugin>
                    <groupId>com.trivago.rta</groupId>
                    <artifactId>cucable-plugin</artifactId>
                        <version>0.0.9</version>
                    <executions>
                        <execution>
                            <id>generate-test-resources</id>
                            <phase>generate-test-resources</phase>
                            <goals>
                                <goal>parallel</goal>
                            </goals>
                            <configuration>
                                <sourceRunnerTemplateFile>src/test/resources/Parallel/cucable.template</sourceRunnerTemplateFile>
                                <sourceFeatures>src/test/resources/ParallelFeature</sourceFeatures>
                                <generatedFeatureDirectory>src/test/resources/Parallel/newFeature</generatedFeatureDirectory>
                                <generatedRunnerDirectory>src/test/java/com.amex.viper.parallel</generatedRunnerDirectory>
                                <numberOfTestRuns>1</numberOfTestRuns>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
                  <plugin>
	        <groupId>org.codehaus.mojo</groupId>
	        <artifactId>build-helper-maven-plugin</artifactId>
	        <version>3.0.0</version>
	        <executions>
	          <execution>
	            <id>add-test-source</id>
	            <phase>generate-test-sources</phase>
	            <goals>
	              <goal>add-test-source</goal>
	            </goals>
	            <configuration>
	              <sources>
	                <source>src/test/java/com.amex.viper.parallel</source>		                
	              </sources>
	            </configuration>
	          </execution>
	        </executions>
  		</plugin>
        
               <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>2.18.1</version>
                    <configuration>
                        <skipTests>true</skipTests>
                    </configuration>
                </plugin> 
           
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-failsafe-plugin</artifactId>
                    <executions>
                        <execution>
                            <id>Run parallel tests</id>
                                <phase>integration-test</phase>
                                <goals>
                                    <goal>integration-test</goal>
                                </goals>
                        </execution>
                    </executions>
                    <configuration>
                        <forkCount>5</forkCount>
                        <testFailureIgnore>true</testFailureIgnore>
                        <reuseForks>false</reuseForks>
                        <argLine>-Dfile.encoding=UTF-8</argLine>
                        <disableXmlReport>true</disableXmlReport>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>net.masterthought</groupId>
                    <artifactId>cucumber-reporting</artifactId>
                    <version>3.12.0</version>
                    <executions>
                        <execution>
                            <id>report</id>
                            <phase>post-integration-test</phase>
                            <goals>
                                <goal>generate</goal>
                            </goals>
                            <configuration>
                                <outputDirectory>src/test/resources/report</outputDirectory>
                                <cucumberOutput>src/test/resources/report/cucumber-report</cucumberOutput>
                                <projectName>My Report</projectName>
                                <buildNumber>1</buildNumber>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
                	
               <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-enforcer-plugin</artifactId>
                    <dependencies>
                        <dependency>
                            <groupId>com.trivago.rta</groupId>
                            <artifactId>your-custom-maven-fail-rule</artifactId>
                            <version>0.0.9</version>
                        </dependency>
                    </dependencies>
                    <executions>
                        <execution>
                            <phase>verify</phase>
                            <goals>
                                <goal>enforce</goal>
                            </goals>
                            <configuration>
                                <rules>
                                    <yourRule implementation="com.example.YourFailRule"/>
                                </rules>
                                <fail>true</fail>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>  
            </plugins>
        </build>
    </profile>
		
		
		
		
		</profiles> 
	

</project>
There is no error message but its not generating the resources

[INFO] --- build-helper-maven-plugin:3.0.0:add-test-source (add-test-source) @ vPOL ---
[INFO] Test Source directory: C:\Users\sjanakir\Desktop\Automation\Scenario\vng\integration_tests. added.
[INFO] 
[INFO] --- cucable-plugin:0.0.9:parallel (generate-test-resources) @ vPOL ---
[INFO] =====================================
[INFO]  Cucable Maven Plugin, version 0.0.9
[INFO] =====================================
[INFO] ? sourceRunnerTemplateFile : src/test/resources/Parallel/cucable.template
[INFO] ? generatedRunnerDirectory : src/test/java/com.amex.viper.parallel
[INFO] ? sourceFeatures           : src/test/resources/ParallelFeature
[INFO] ? generatedFeatureDirectory: src/test/resources/Parallel/newFeature
[INFO] ? numberOfTestRuns         : 1
[INFO] 
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ vPOL ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 331 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.5:testCompile (default-testCompile) @ vPOL ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ vPOL ---
[INFO] Tests are skipped.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] -------------------
-

**Comment by laxersaz** [comment]
Hello! Have you tried rubbinf the Cucable example project in https://github.com/laxersaz/cucable-test-project? Because this one works for sure.
Are you sure the runner directory is correct? It should be a path not a package.

**Comment by laxersaz** [comment]
No reaction so I will close this for now.
