### ISSUE TITLE
Filter generation of feature runners with cucumber tags

### ISSUE THREAD

**Issue by schmalzi-compax** [trivago/cucable-plugin#31]
First of all, it's a really cool plugin, thank you very much :)
Would it be possible to filter the generation of runners with cucumber tags configurable in the pom.xml? 
The same feature already exists in cucumber-slices-maven-plugin and my use case is the @ignore tag. At the moment for all scenarios labeled with @ignore a runner will generated anyway which leads to unnecessary overhead and furthermore to errors in your reporting plugin cluecumber (nullpointerexception due to an empty json output file)

**Comment by laxersaz** [comment]
Thanks for this suggestion - I will check what's possible 🙂

**Comment by laxersaz** [comment]
Version 0.1.0 of Cucable will include the excludeScenarioTags option. For a preview check this branch:
https://github.com/trivago/cucable-plugin/tree/0.1.0

**Comment by schmalzi-compax** [comment]
Cool, i'll take a look asap.

**Comment by laxersaz** [comment]
The question for me is if Cucable should support:
- Not generating runners and features for passed tags
- Only generating runners and features for passed tags
- Both

For supporting both, this would mean having two properties like

```
<excludeScenarioTags>
  <param>@skip</param>
</excludeScenarioTags>
```

```
<includeScenarioTags>
  <param>@generateOnlyThis</param>
</includeScenarioTags>
```

**Comment by schmalzi-compax** [comment]
Yes, i know what you mean, my colleagues and i already discussed the same questions.
Other plugins like cucumber-slices-maven-plugin support the include variant and i would prefer an include list of tags because i think it's more usable.

**Comment by laxersaz** [comment]
That's right. I thought about that too and I will change it 😁

**Comment by laxersaz** [comment]
@schmalzi-compax this will be in version 0.1.1 that I just released. Should be available within the next 2 hours. Please note that 0.1.0 will also be there but 0.1.1 is the fixed version.

**Comment by schmalzi-compax** [comment]
I just verified it with version 0.1.1, works great :)
There is still one last question, because I fell into this trap. My cucumber files were tagged at feature level, so my first run with an include filter wasn't successful. In cucumber feature level tags will be inherited to its scenarios, so should not consider include/excludeScenarioTags tags at feature level too?

**Comment by laxersaz** [comment]
Really good comment since I wasn't aware of this inheritance. I treat feature tags a little different than scenario tags at the moment. Will certainly try this out and change the behavior accordingly.

**Comment by laxersaz** [comment]
@schmalzi-compax I opened issue https://github.com/trivago/cucable-plugin/issues/33 after verifying the behavior. Will be changed in 0.1.2
