### ISSUE TITLE
Tag filters should take feature tags into account

### ISSUE THREAD

**Issue by laxersaz** [trivago/cucable-plugin#33]
http://blog.picklespro.com/2016/11/24/anatomy-of-a-gherkin.html

Feature tags are inherited by its scenarios so they need to be considered in filtering as well.

**Comment by laxersaz** [comment]
Fixed in version 0.1.2 (on maven central soon)

**Comment by schmalzi-compax** [comment]
verified with version 0.1.2, thanks again
