### ISSUE TITLE
Issue with Scenario outline in combination with data table

### ISSUE THREAD

**Issue by s1apped** [trivago/cucable-plugin#36]
Hi,

I'm running cucable successfully with normal scenarios.  But I'm having problem with scenario outline.
In execution log I see below:
{\"name\":[\"<name>\"]
instead of
{\"name\":[\"Adam"]

Looks like parameter isn't read/converted properly?

**Comment by laxersaz** [comment]
Hello @s1apped ,

In general, Cucable should not have problems with outlines.
Could you give me the complete scenario (or a similar one) so I can test it, please?

Thanks a lot,
Benjamin

**Comment by s1apped** [comment]
hello @laxersaz ,

I'm using 0.1.2 but I tried previous versions also.
Below is a small example.

  @Test
  Scenario Outline: Test

    Given As a User "test" I'm authorized
    Then Account is created with data:
      | taskId | accountName | type 	| scopeId   |
      | 515555 | Name        | <type>   | <scopeID> |

    Examples:
      | type          | scopeID |
      | Master 	| 3            |
      | Slave 	| 3            |

Feature generated by cucable from generatedFeatureDirectory:
@Test
Scenario: Test

    Given As a User "test" I'm authorized
    Then Account is created with data:
      | taskId | accountName | type 	| scopeId   |
      | 515555 | Name        | <type>   | <scopeID> |

# Generated by Cucable

**Comment by laxersaz** [comment]
OK, I see the problem in this case. So it is happening when using a scenario outline with a data table in combination with an example table.
I will look into that ASAP. Thanks for reporting!

**Comment by s1apped** [comment]
Great. Thanks for looking into it!

**Comment by laxersaz** [comment]
I already created a fix for this issue - you can check the code in
https://github.com/trivago/cucable-plugin/compare/0.1.3?expand=1

As soon as the unit tests are done, I will release a new Cucable - probably tomorrow.

**Comment by laxersaz** [comment]
This issue is fixed in Cucable 0.1.3 which should be on Maven Central in the next 2 hours.

**Comment by s1apped** [comment]
Awesome. Thank you @laxersaz !
