### ISSUE TITLE
Ability to provide Tags via command line

### ISSUE THREAD

**Issue by avyasbms** [trivago/cucable-plugin#41]
When test are executed from command line (e.g. mvn verify -Pparallel ) Tags can't be provided on command line. 

How can it be done?

Also in addition to tags if single feature can also be configurable via command line it would help execute large features parallel as well.

**Comment by laxersaz** [comment]
You can use system properties for that. So e.g. if you pass your parameters like this
`mvn verify -Pparallel -Dtags=@tag1,@tag2`
you can use this property inside your pom file like this:
'<includeScenarioTags>${tags}</includeScenarioTags>'
The same applies to the features.

For this to work, add a properties block in your pom that declares the passable properties:
```
    <properties>
        <tags/>
    </properties>
```

This way you can also give them default values in case they aren't passed through the command line:
```
    <properties>
        <tags>@live</tags>
    </properties>
```

**Comment by avyasbms** [comment]
_Awesome_  👍

**Comment by avyasbms** [comment]
Hello @laxersaz, is there any way we can use cucumber Tag Expressions ?
https://docs.cucumber.io/tag-expressions/ 
If not then How can we only execute Scenarios with following cases?
-Tag1 and Tag2
-Tag1 or Tag2

**Comment by laxersaz** [comment]
You can add cucumber tags in your runner template as well. The Cucable tags are just affecting the feature and runner generation whereas Cucumber tags decide what to run.

**Comment by laxersaz** [comment]
@avyasbms , Cucable 1.4.0 now supports tags connected with _and_ or _or_  :-)

**Comment by avyas** [comment]
Can you please provide an example?

**Comment by laxersaz** [comment]
@avyas , it is all in the documentation and also included in the example project...
https://github.com/trivago/cucable-plugin#includescenariotags
