### ISSUE TITLE
Global before execution

### ISSUE THREAD

**Issue by miranroxti** [trivago/cucable-plugin#57]
### Enhancement

Hello,

I was wondering if it would be possible to add an option to make a global before step. I'd like to download something before my test execution. At this moment it has to download it separately for each run. This could maybe be done by adding an option to the profile of a java file that would be executed before the parallel runs get started.

Thanks in advance,
Rob

**Comment by laxersaz** [comment]
Why can't you just download this file automatically before your tests actually run? Everything that has to do with preparing the test environment should be done before the actual test invocation.
Having this in Cucable would be out of its scope (splitting Cucumber features into chunks).
