### ISSUE TITLE
Data tables not being supported

### ISSUE THREAD

**Issue by 1dson** [trivago/cucable-plugin#6]
Could you please add support for data tables. Currently the plugin deals with example tables but if a scenario has got a data table the plugin copies the scenario but omits the table.

**Comment by laxersaz** [comment]
Will do, thanks for reporting!

**Comment by laxersaz** [comment]
In my current branch I implemented data table capabilities. This will probably be released next week.

**Comment by 1dson** [comment]
Thanks for the update and quick turnaround :-)

**Comment by laxersaz** [comment]
Release 0.0.6 supports data tables. It should be available on Maven Central in the next 2 hours.

**Comment by 1dson** [comment]
Thanks
