### ISSUE TITLE
Can this Plugin be used in Serenity? Generate reports and live documentation?

### ISSUE THREAD

**Issue by mpuertao** [trivago/cucable-plugin#60]
### Expected behavior

 I need run test in parallel for scenario with Serenity and keep living documentation - reports 

### Actual behavior

Actually, I execute test in parallel for Runner

**Comment by laxersaz** [comment]
This plugin can be used with Serenity. However, I am pretty sure Serenity‘s reporting cannot handle the sliced scenarios correctly. Maybe try my Cluecumber report plugin instead if it doesn‘t work: https://github.com/trivago/cluecumber-report-plugin

**Comment by mpuertao** [comment]
Thank you very much for the response. 
Excellent work and documentation for this plugin, congratulations.

**Comment by laxersaz** [comment]
Thanks a lot!
