### ISSUE TITLE
NPE handling - incorrect Scenario Outline placeholder

### ISSUE THREAD

**Issue by daczczcz1** [trivago/cucable-plugin#66]
When parsing a Scenario Outline with a placeholder is not present in the examples table, there is a NPE. 

```
Scenario Outline: <badplaceholder>
    When #some steps

Examples:
|placeholder1|placeholder2|
|...         |            |
```
This results in a NPE during parsing of features.

> [ERROR] Failed to execute goal com.trivago.rta:cucable-plugin:0.1.9:parallel (generate-test-resources) on project *******: Execution generate-test-resources of goal com.trivago.rta:cucable-plugin:0.1.9:parallel failed. NullPointerException -> [Help 1]
> org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.trivago.rta:cucable-plugin:0.1.9:parallel (generate-test-resources) on project *******: Execution generate-test-resources of goal com.trivago.rta:cucable-plugin:0.1.9:parallel failed.
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
> 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
> 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
> 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
> 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
> 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
> 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
> 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
> 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
> 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
> 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
> Caused by: org.apache.maven.plugin.PluginExecutionException: Execution generate-test-resources of goal com.trivago.rta:cucable-plugin:0.1.9:parallel failed.
> 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
> 	... 20 more
> Caused by: java.lang.NullPointerException
> 	at com.trivago.rta.gherkin.GherkinDocumentParser.substituteScenarioNameExamplePlaceholders(GherkinDocumentParser.java:400)
> 	at com.trivago.rta.gherkin.GherkinDocumentParser.getSingleScenariosFromOutline(GherkinDocumentParser.java:212)
> 	at com.trivago.rta.gherkin.GherkinDocumentParser.getSingleScenariosFromFeature(GherkinDocumentParser.java:135)
> 	at com.trivago.rta.features.FeatureFileConverter.convertToSingleScenariosAndRunners(FeatureFileConverter.java:127)
> 	at com.trivago.rta.features.FeatureFileConverter.convertToSingleScenariosAndRunners(FeatureFileConverter.java:93)
> 	at com.trivago.rta.CucablePlugin.execute(CucablePlugin.java:129)
> 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
> 	... 21 more

 Ideally, the user would like to see some message pointing to the file and scenario causing the problem.

**Comment by daczczcz1** [comment]
@laxersaz If you agree on the matter of the issue, I would like to work on this (of course if you let me :)).

**Comment by laxersaz** [comment]
Sure go for it :-)
