### ISSUE TITLE
Being able to set "include/exclude tags" in the command line

### ISSUE THREAD

**Issue by jsa34** [trivago/cucable-plugin#67]
It would be really helpful to not only be able to specify the tags for including/excluding in the test run in the POM config, but would also be great to be able to set this at run through the command by passing some parameters. This would help with running specific tests/suites and excluding others on demand.

Just an improvement :)

**Comment by laxersaz** [comment]
This is already possible. See my answer here:
https://github.com/trivago/cucable-plugin/issues/41
