### ISSUE TITLE
Enhancement Request - Capability to add glue path in the template from pom

### ISSUE THREAD

**Issue by prasant-sethi** [trivago/cucable-plugin#71]
I must say this is a cool plug in and thanks for the great work.
I have a situation where I want to add the glue path from pom. Let me tell why?

Here is my package structure:
com.feature
- login
   - loginstep.java
- logout
   - logout.java

I want to provide the glue path 
glue = "com.feature.login" or "com.feature.logout"

I can't give both because the before in each step definition runs for all the files.

Can you add a capability to pass the glue path from pom to the template?

Thanks !

**Comment by laxersaz** [comment]
Interesting suggestion, @prasant-sethi ! I will look at this one for sure.

**Comment by laxersaz** [comment]
I am thinking about supporting custom placeholders and arguments so users can be free to pass whatever they want to the template.

**Comment by laxersaz** [comment]
Release in 1.1.0

**Comment by prasant-sethi** [comment]
This is great news ! I tried adding the customPlaceholders tag inside the plugin configuration inside the pom file. Showing error as 'element is not allowed here'.

**Comment by laxersaz** [comment]
Please check out the example project in https://github.com/trivago/cucable-plugin/tree/master/example-project to see a working example.
