### ISSUE TITLE
Exception when building in travis

### ISSUE THREAD

**Issue by SumanpreetJhinjer** [trivago/cucable-plugin#75]
Hi Lax,

I am facing issue while building my project in travis.
It's throwing below exception in travis....

[ERROR] Failed to execute goal com.trivago.rta:cucable-plugin:1.1.0:parallel (generate-test-resources) on project restassured-cucumber-java: src\test\resources\features\ is not a feature file or a directory. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

The same is running fine in Local and jenkins....but not in travis...not sure if its a plugin issue or travis issue
But any help will be appreciated

**Comment by laxersaz** [comment]
Hi! If you use forward slashes instead of back slashes it will work on all systems.
