### ISSUE TITLE
Rerun.txt generated from failsafe plugin are generated empty(on a failing scenario).

### ISSUE THREAD

**Issue by kunalnovice** [trivago/cucable-plugin#76]
**Describe the bug**
Rerun.txt files are generated empty.

My CucumberTemplate includes reference like  "rerun:target/RerunFiles/[CUCABLE: RUNNER]_rerun.txt"

**To Reproduce**
1. My CucumberTemplate includes reference like  "rerun:target/RerunFiles/[CUCABLE:RUNNER].txt"
2. Generated Runner Class are correctly mentioning the XXX_rerun.txt files
3. on executing integration test with a failsafe plugin, failing scenario correctly generates the XXX_rerun.txt files.
4. entry for the feature file path and line number is missing from XXX_rerun.txt

If I manually run the generated runner file outside the plugin, the XXX_rerun.txt contains the expected content.

**Expected behavior**
whilst the generated runner file are executed via the failsafe plugin, it is expected that on failing scenario rerun.txt should be generated with faulty feature path and line number(if configured)

**Attachments**
If applicable, add an attachment to help explain your problem.

**Additional context**
If I manually run the generated runner file outside the plugin, the XXX_rerun.txt contains the expected content.
any suggestion will help. thanks

**Comment by laxersaz** [comment]
Hello @kunalnovice!
Thanks for your report. I will look into it and let you know. 
Best, 
Benjamin

**Comment by laxersaz** [comment]
Hello again,
if I understand your setup correctly, this problem seems to be related to your setup and not Cucable. Cucable generates Cucumber compliable feature files, nothing more. 🤨 Have you tried running a Cucable generated feature manually?

**Comment by kunalnovice** [comment]
thanks for your quick feedback. It was mistake at my end.  I went with cucuableTemplate as given in the repo. and in the process missed out to implement 'strict' cucumberoptions.
'rerun' format was loosely related to strict in a way that strict being default enabled as false was not marking the scenario as failed(for pending and undefined steps) and hence rerun text file was generated empty.

Thanks for your effort to put such a fantastic plugin.

**Comment by laxersaz** [comment]
Thanks a lot for your kind words 🙂
