### ISSUE TITLE
Cucable desiredNumberOfRunners with value 2 is not running two runners in parallel(one runner has chrome features and second runner has ie features) both are executing in sequence not in parallel thread

### ISSUE THREAD

**Issue by pmaddi2** [trivago/cucable-plugin#77]
**Describe the bug**

**To Reproduce**
1. Create a scenario with...
2. Run Cucable
3. See error

**Expected behavior**

**Attachments**
If applicable, add an attachment to help explain your problem.

**Additional context**

**Comment by laxersaz** [comment]
Hello, please provide more information about your setup (unfortunatelly you didn't fill in any of the descriptions in this ticket). Cucable itself is not running any features but just preparing the test data. So your problem is probably related to any step after Cucable.

**Comment by pmaddi2** [comment]
Please accept my apologies, added this issue in hurry, hence not able to provide full details. 
Here are the details:-
Below POM and template created two runners for Scenario outline with 10 rows in example(5 for ie and 5 for chrome). (like:- ie, chrome, ie, chrome, ie, chrome, ie, chrome, ie, chrome,) and it distributed ie and chrome separately into two runners.  Could you please review and advise what changes i have to do in-order to run bother runners in parallel (just like Testng or junit parallel execution).
Runner template:-
package parallel.runners;

import org.junit.runner.RunWith;

import cucumber.api.CucumberOptions;
import cucumber.api.junit.Cucumber;

//tags = {"[CUCABLE:CUSTOM:foo]"}
@CucumberOptions(
		monochrome = false,
        features = {"src/test/java/parallel/[CUCABLE:FEATURE].feature"},
        plugin = {"json:target/[CUCABLE:RUNNER].json"},
    	glue = {"org.app.junit_testset.stepdefs"},
		strict = false,
	    dryRun = false
)
public class [CUCABLE:RUNNER] {
	
}

Below is the POM.xml:-

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.app</groupId>
    <artifactId>junit_testset</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>jar</packaging>
    <name>Cucumber-Java-JUnit Project</name>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<maven.failsafe.plugin.version>2.20.1</maven.failsafe.plugin.version>
		<maven.build.helper.plugin.version>3.0.0</maven.build.helper.plugin.version>
		<junit.version>4.12</junit.version>
		<cucumber.version>1.2.5</cucumber.version>
		<java.version>1.8</java.version>
		<forkinstancecount>2</forkinstancecount>
		<generated.runner.directory>${project.build.directory}\parallel\runners</generated.runner.directory>
		<generated.feature.directory>${project.build.directory}\parallel\features</generated.feature.directory>
	</properties>
    <dependencies>
       <dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-java</artifactId>
			<version>${cucumber.version}</version>
		</dependency>
		
		
		<dependency>
		    <groupId>javax.mail</groupId>
		    <artifactId>mail</artifactId>
		    <version>1.4.7</version>
		</dependency>
		        
        <dependency>
            <groupId>info.cukes</groupId>
            <artifactId>cucumber-core</artifactId>
            <version>${cucumber.version}</version>
        </dependency>
        
        
		<dependency>
		    <groupId>info.cukes</groupId>
		    <artifactId>gherkin</artifactId>
		    <version>2.12.2</version>
		    <scope>provided</scope>
		</dependency>
		        
        
		<dependency>
		    <groupId>info.cukes</groupId>
		    <artifactId>cucumber-junit</artifactId>
		    <version>${cucumber.version}</version>
		    <scope>test</scope>
		</dependency>
		        
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
         
        
		<dependency>
		    <groupId>io.cucumber</groupId>
		    <artifactId>cucumber-jvm-deps</artifactId>
		    <version>1.0.6</version>
		    <scope>provided</scope>
		</dependency>

		
		<dependency>
		    <groupId>org.seleniumhq.selenium</groupId>
		    <artifactId>selenium-java</artifactId>
		    <version>3.13.0</version>
		</dependency>

    </dependencies>
    	
<build>
	<plugins>
		<plugin>
			<groupId>com.trivago.rta</groupId>
			<artifactId>cucable-plugin</artifactId>
			<version>1.1.0</version>
			<executions>
				<execution>
					<id>generate-test-resources</id>
					<phase>generate-test-resources</phase>
					<goals>
						<goal>parallel</goal> 
					</goals>
				</execution>
			</executions>
			<configuration>
			
			
			<sourceRunnerTemplateFile>src/test/java/org/app/junit_testset/template/cucable.template</sourceRunnerTemplateFile>
			
			<sourceFeatures>src/test/resources/org/app/junit_testset/features/Registration.feature</sourceFeatures>
			
			
			
			
			<generatedFeatureDirectory>${generated.feature.directory}\parallel\features</generatedFeatureDirectory>
			<generatedRunnerDirectory>${generated.runner.directory}\parallel\runners</generatedRunnerDirectory>
			
			
		        <numberOfTestRuns>1</numberOfTestRuns>
		        <includeScenarioTags>
		            <param>@ie</param>
		            <param>@chrome</param>
		        </includeScenarioTags>                                
		        <excludeScenarioTags>
		            <param>@skip</param>
		        </excludeScenarioTags>
		        <logLevel>compact</logLevel>
		        <desiredNumberOfRunners>${forkinstancecount}</desiredNumberOfRunners>  
		        <customPlaceholders>
				    <environment>ABC</environment>
				</customPlaceholders>
			
						
			
			          
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
		</configuration>
	</plugin>
			
	<plugin>
	    <groupId>org.codehaus.mojo</groupId>
    	<artifactId>build-helper-maven-plugin</artifactId>
		<version>${maven.build.helper.plugin.version}</version>
		<executions>
			<execution>
				<id>add-test-source</id>
				<phase>generate-test-sources</phase>
				<goals>
					<goal>add-test-source</goal>
				</goals>
				<configuration>
					<sources>
						<source>${generated.runner.directory}\parallel\runners</source>
					</sources>
				</configuration>
			</execution>
		</executions>
	</plugin>
 	<plugin>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-surefire-plugin</artifactId>
			<version>2.22.0</version>

	</plugin>
	<plugin>
		<groupId>org.apache.maven.plugins</groupId>
		<artifactId>maven-failsafe-plugin</artifactId>
		<version>${maven.failsafe.plugin.version}</version>
		<executions>
			<execution>
			<id>Run parallel tests</id>
            <phase>integration-test</phase>
			<goals>
			<goal>integration-test</goal>
			</goals>
			<configuration>
				<forkCount>${forkinstancecount}</forkCount>
				<testFailureIgnore>true</testFailureIgnore>
	            <threadCount>${forkinstancecount}</threadCount>
	            <parallel>classes</parallel>
	            <argLine>-Dfile.encoding=UTF-8</argLine>
	            <disableXmlReport>true</disableXmlReport>
			</configuration>
			</execution>
		</executions>
		</plugin>
		<plugin>
			<groupId>org.apache.maven.plugins</groupId>
		    <artifactId>maven-compiler-plugin</artifactId>
		    <version>3.8.0</version>
			<configuration>
				<source>1.8</source>
				<target>1.8</target>
			</configuration>
		</plugin>
		
		<plugin>
			<groupId>com.trivago.rta</groupId>
			<artifactId>cluecumber-report-plugin</artifactId>
			<version>1.2.1</version>
			<executions>
				<execution>
					<id>report</id>
					<phase>post-integration-test</phase>
					<goals>
						<goal>reporting</goal>
					</goals>
				</execution>
			</executions>
			<configuration>
				<sourceJsonReportDirectory>${project.build.directory}</sourceJsonReportDirectory>
				<generatedHtmlReportDirectory>${project.build.directory}\generated-report</generatedHtmlReportDirectory>
				<customParameters>
				    <My_Custom_Parameter>Google test</My_Custom_Parameter>
				    <Test_Parameter>https://google.com</Test_Parameter>
				</customParameters>
			</configuration>
		</plugin> 
	</plugins>
</build>
	


    
</project>

**Comment by laxersaz** [comment]
Please use the provided POM in the example project as a starting point. Did you try running it with 
```
 <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>${maven.failsafe.plugin.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                        </goals>
                        <configuration>
                            <forkCount>2</forkCount>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

**Comment by pmaddi2** [comment]
Yes, I tried with this as well, not executed in parallel.

**Comment by laxersaz** [comment]
Could you attach an example project zip file that I can try? Otherwise it is pretty hard to debug.

**Comment by pmaddi2** [comment]
I can't attach here, could you please share your email id to send. or else I have to modify feature file & step defs with google/social sites. I'll update with social site scenarios share you at earliest.

**Comment by pmaddi2** [comment]
Hi laxersaz,

I just realized that this above POM is not triggering test execution phase, it is just generating resources and compiling. I tried with maven clean verify. without cucable plugin configuration able to trigger test phase . Could you please review and advise what are the changes I have to make in POM to enter into test phase.

**Comment by pmaddi2** [comment]
I tried with this either one of these templates:- still not worked.
package org.app.automationcucable.runners;

import cucumber.api.CucumberOptions;
import cucumber.api.junit.Cucumber;

import org.junit.runner.RunWith;

//tags = {"[CUCABLE:CUSTOM:foo]"}
@RunWith(Cucumber.class)
@CucumberOptions(
		monochrome = false,
        features = {"C:/Automation/automationcucable/src/test/resources/parallel/[CUCABLE:FEATURE].feature"},
        plugin = {"json:target/[CUCABLE:RUNNER].json"},
    	glue = {"org.app.automationcucable.stepdefs"},
		strict = false,
	    dryRun = false
)
public class [CUCABLE:RUNNER] {
		
}
//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
package org.app.automationcucable.runners;

import cucumber.api.CucumberOptions;
import cucumber.api.junit.Cucumber;

import org.junit.runner.RunWith;

//tags = {"[CUCABLE:CUSTOM:foo]"}
@CucumberOptions(
		monochrome = false,
        features = {"C:/Automation/automationcucable/src/test/resources/parallel/[CUCABLE:FEATURE].feature"},
        plugin = {"json:target/[CUCABLE:RUNNER].json"},
    	glue = {"org.app.automationcucable.stepdefs"},
		strict = false,
	    dryRun = false
)
public class [CUCABLE:RUNNER] {
		
}

**Comment by laxersaz** [comment]
Please try the Cucable example project first as this also runs the tests (using `mvn clean verify`). If this works for you (without making any changes), you can use it to expand it to your test case. Since you said that Cucable is generating the test sources correctly for you, I unfortunatelly cannot help you more with your matter of running the tests as this would be beyond the project's scope.
