### ISSUE TITLE
what is the threshold for cucable plugin to run parallel tests?  

### ISSUE THREAD

**Issue by deepthi-ravindra** [trivago/cucable-plugin#78]
We have 215 scenarios running parallely and have noticed they all timeout as and when we add tests to the suite.

Is there a limit for number of scenarios to be run parallely?

Cheers

**Comment by laxersaz** [comment]
Hello,
Cucable does not run any tests, it just splits Cucumber scenarios into the smallest possible test cases so this question is not related to this project.

The parallel limit for failsafe or surefire is determined by your system resources.
