### ISSUE TITLE
cucumber-report folder which would have all json report files is not getting generated

### ISSUE THREAD

**Issue by Galileo1** [trivago/cucable-plugin#83]
**Describe the bug**
Example project does not generate cucumber-report folder which would have all json report files.

**To Reproduce**
1. Clone the project.
2. Modify the pom.xml file to add the configuration for [cluecucumber ](https://github.com/trivago/cucable-plugin#3-aggregation-of-a-single-test-report-after-all-test-runs)plugin 
3. Change the ${cluecumber.report.version} to version 1.5.0
4. Execute "mvn install"
5. Error -> `[ERROR] Failed to execute goal com.trivago.rta:cluecumber-report-plugin:1.5.0:reporting (report) on project cucable-test-project: Unable to traverse JSON files in cucable-plugin-master\example-project\target/cucumber-report`

**Expected behavior**
the target folder should have the cucumber-report folder with all the json reports for each generated scenario.And cluecucumber plugin should have consolidated the reports into single report.

**Comment by laxersaz** [comment]
You need to specify in your Cucumber runner that you want to generate JSON files. This example project is just to show how Cucable works so this is expected behavior.

Please consider the [Cluecumber Prerequisites]https://github.com/trivago/cluecumber-report-plugin#prerequisites) for generating JSON files.

**Comment by laxersaz** [comment]
Just a second :-)

**Comment by laxersaz** [comment]
Hello @Galileo1 

I investigated this and you are correct. I pushed an updated version of the example project which generates the JSON files as expected.
Thanks a lot for letting me know!

**Comment by Galileo1** [comment]
Thanks @laxersaz

**Comment by smekapati** [comment]
Hi I am getting the same issue 
Failed to execute goal com.trivago.rta:cluecumber-report-plugin:1.8.1:reporting (report) on project digital_bdd_cucumber: Unable to traverse JSON files in C:\Application\digital_bdd_cucumber\target/cucumber-parallel ->

its working fine in my colleague machine , I deleted my POM and .m2 repository taken his POM and .m2 repository and updated in my system, still facing the same issue I checked all the eclipse configuration both using Oxygen

**Comment by laxersaz** [comment]
Are you sure your json file location is correct? And are there actually json files in there?
