### ISSUE TITLE
Issues with parallelization mode "features"

### ISSUE THREAD

**Issue by Robin-M** [trivago/cucable-plugin#85]
I found your plugin while searching for a good alternative for our current parallelization plugin of which the latest versions aren't compatible with our project anymore. I like the parallelization mode "features" because then I can keep using our current Cucumber reporting tool which give us the best view of the results. However, I have a few issues which prevent me from using this plugin:

1. I have many features in different directories with the same filename. Because all features are generated in target/parallel/features, only one of every filename is stored. Could you add a feature counter just like the scenario counter in parallelization mode "scenarios" to prevent files being overwritten?
1. The generated feature file is not the same as the original file. On some environments special characters like € are replaced by ??? which causes the scenarios to fail. Scenario Outlines are split into single scenarios with the same name which is confusing in the final Cucumber report. These problems seem easy to solve by just copying the original feature file to the generated feature directory or by using the original feature files when in parallelization mode "features".

**Comment by laxersaz** [comment]
I fixed the two mentioned bugs and this will be included in the 1.3.0 release next week.

**Comment by laxersaz** [comment]
Fixed with 1.3.0
