### ISSUE TITLE
Logically ANDing and ORing Tags in Cucumber

### ISSUE THREAD

**Issue by jaydeepqa** [trivago/cucable-plugin#87]
If we mention multiple tags under the includeScenarioTags then it behaves like Cucumber ORing Tags but if we want to use Cucumber ANDing Tags then how to achieve the same?
For clarity I am talking about Logically ANDing and ORing Tags in Cucumber.

**Comment by laxersaz** [comment]
This is not supported (yet). You can achieve the same by using Cucumber tag expressions in your custom runner, though.
The Cucable includeScenarioTags just specify which scenarios should be _generated_. If you want to _run_ a subset of those with multiple tags connected with _and_, this has to be achieved within the runners.
However, it is a good idea to support this behaviour in Cucable as well. I will create a task for this.
