### ISSUE TITLE
Support includeScenarioTags with _and_ and _or_

### ISSUE THREAD

**Issue by laxersaz** [trivago/cucable-plugin#88]
Created from #87

**Comment by laxersaz** [comment]
This is planned for a larger Cucable update which will be started next week.

**Comment by jaydeepqa** [comment]
Thanks for the update.

**Comment by laxersaz** [comment]
The implementation for this feature is done. Now working on the two remaining ones to release together.

**Comment by jaydeepqa** [comment]
Hey thanks a lot for letting me know, your effort is much appreciated.

**Comment by yuraku** [comment]
hi @laxersaz . I'm trying to specify multiple tags in the pom, but it's failed as not recognized 
<img width="731" alt="cucable_tags" src="https://user-images.githubusercontent.com/5933211/59073067-35470c80-88ce-11e9-89bb-75172ffd5227.png">

could you please point me to what is specified wrong? thanks in advance

**Comment by laxersaz** [comment]
It should still work when you run it.
If you use IntelliJ, you can suppress it by adding this line before your property:
`<!--suppress UnresolvedMavenProperty -->`

By the way, this does not happen if you pass in the property from the outside with Maven's `-D` flag.

**Comment by yuraku** [comment]
Thanks, @laxersaz for your reply. I've tried your suggestion and it seems doesn’t work for me, please see screenshot.
https://prntscr.com/o16zs8
Also about the parameter flag `-D`, do you mean that it will not work in case of multiple tags, or even a single one, like `-Dincluded='@footer'`

**Comment by laxersaz** [comment]
You are using an outdated Cluecumber version which doesn't support tag expressions yet. Please check your version.

**Comment by yuraku** [comment]
thanks for you reply. After update started working 👍🏻
