### ISSUE TITLE
Question on JVM forking and managing parallelization using this plugin

### ISSUE THREAD

**Issue by Galileo1** [trivago/cucable-plugin#90]
My understanding: The parallelization in this plugin is left on to surefire and it's configuration parameters. It is not inherently built into this plugin as such I believe. 

Would you be able to emphasis on the best practice of how this plugin along with the capability of surefire failsafe plugin(forkCount etc) can be used properly.I am facing issues in how to optimally utilize this plugin. 

- What forkCount limit should I use?
- Each forkcount == each JVM process. What happens when test cases are more than forkcount does the remaining test cases run sequentially? 

Any reference document/blog that you have already posted in this context?

**Comment by laxersaz** [comment]
Hello, yes you are right, the parallel runs have to be handled by surefire or failsafe - Cucable just splits up the scenarios and generates the necessary runners. If you have 100 test cases and 2 forks, each fork might run about 50 test cases sequentially. It can also be more or less depending on the run time of each test case - whenever one fork (JVM) is idle, the next test case will run there.

There is no advice I can give in terms of what fork count to use. It heavily depends on the resources your test framework needs and the processors and memory of your machines.
