### ISSUE TITLE
Using ${loremipsum} inside table cell content throws ParseException

### ISSUE THREAD

**Issue by valdeziscoming** [trivago/cucable-plugin#94]
When using variable substitution in a table data section e.g.

  @framework
  @nobrowser
  Szenario: Datumsfunktion
    Wenn Freemarker-> ich Daten für heute, morgen und gestern über die Datumsfunktionen generiere
      | heute      | morgen               | gestern               |
      | ${heute()} | ${datum(heute(),+1)} | ${datum(heute(), -1)} |
    Dann Freemarker-> sind die Daten über die Datumsfunktion korrekt befüllt

(freemarker method calls for dynamic values - handled with step implementation...)

** Error
cucable throws a ParseException, when generating scenarios from the included feature file

**Expected behavior**

Arbitrary table cell content should be allowed..

(Broken since version 1.3.1 ?)

**Comment by laxersaz** [comment]
Hi @valdeziscoming ,

thanks a lot for reporting. This will be tackled for version 1.3.2

Best,
Benjamin

**Comment by valdeziscoming** [comment]
Nice ! Thanks for this great plugin btw. and for your fast response time !

BR, Peter

**Comment by laxersaz** [comment]
I fixed this one and will push the new version of Cucable tomorrow.

**Comment by laxersaz** [comment]
Released 1.3.2 - it should be on central soon. Please let me know if this fixes it.

**Comment by valdeziscoming** [comment]
it's fixed, thanks again !
