### ISSUE TITLE
Retry configuration and Report modification in Trivago Cucuable Plugin

### ISSUE THREAD

**Issue by rahulbommanaboina** [trivago/cucable-plugin#99]
**Is your feature request related to a problem? Please describe.**
I have gone through extended cucumber options ,which has retry count associated to it , but the report generation is not so amazing like yours :) , and also i would like to change and add few other columns in the report which is getting generated , is there a way we can do that ? Attaching a screenshot which edited directly in the inspect panel of chrome. 

If retry is possible and column is added to the report with Retry as header it would be wonderful to use the plugin which serves all functionalities.

![capture](https://user-images.githubusercontent.com/29060552/53952120-07e39a80-40f6-11e9-853c-430f6ffd3b26.PNG)

**Comment by laxersaz** [comment]
This question is unrelated to Cucable.

**Comment by rahulbommanaboina** [comment]
@laxersaz  Thanks for the response , i raised as a feature request !
